### PR TITLE
Fixes #926 - bad StringBuffer reuse in websocket/spec/servercontainer upgradeHttpToWebSocketTest

### LINKED ISSUE #926: websocket/spec/servercontainer/upgradehttptowebsocket uses Object.equals() instead of MessageValidator.checkSearchStrings()
The code in [websocket/spec/servercontainer/upgradehttptowebsocket/WSClient.java](https://github.com/eclipse-ee4j/jakartaee-tck/blob/master/src/com/sun/ts/tests/websocket/spec/servercontainer/upgradehttptowebsocket/WSClient.java) is using
[receivedMessageString.toString().equals(MESSAGE_TEXT)](https://github.com/eclipse-ee4j/jakartaee-tck/blob/master/src/com/sun/ts/tests/websocket/spec/servercontainer/upgradehttptowebsocket/WSClient.java#L82) instead of
MessageValidator.checkSearchStrings(MESSAGE_TEXT).
This causes the websocket/spec/servercontainer/upgradehttptowebsocket test to fail because
[receivedMessageString variable is static](https://github.com/eclipse-ee4j/jakartaee-tck/blob/master/src/com/sun/ts/tests/websocket/spec/servercontainer/upgradehttptowebsocket/WSClient.java#L38) and this test is executed in three TCK vehicles.
[Appending of MESSAGE_TEXT](https://github.com/eclipse-ee4j/jakartaee-tck/blob/master/src/com/sun/ts/tests/websocket/spec/servercontainer/upgradehttptowebsocket/WSClient.java#L107)  cannot pass equals check in second and third TCK vehicle.

Here is the test failure:

[javatest.batch] 04-12-2022 21:19:08:  TRACE: #######  Value of harness.socket.retry.count is "10"
[javatest.batch] 04-12-2022 21:19:08:  TRACE: #######  Value of harness.log.port is "2000"
[javatest.batch] 04-12-2022 21:19:08:  TRACE: #######  Actual bind value of harness.log.port is "2000"
[javatest.batch] 04-12-2022 21:19:08:  TRACE: in custom vehicle so call on EETest.
[javatest.batch] 04-12-2022 21:19:08:  TRACE: *** in EETest.run(argv,p)
[javatest.batch] 04-12-2022 21:19:08:  TRACE: TESTCLASS=com.sun.ts.tests.websocket.spec.servercontainer.upgradehttptowebsocket.WSClient
[javatest.batch] 04-12-2022 21:19:08:  TRACE: ** IN getRunMethod: testClass=com.sun.ts.tests.websocket.spec.servercontainer.upgradehttptowebsocket.WSClient
[javatest.batch] 04-12-2022 21:19:08:  TRACE: ** IN getRunMethod: testname=upgradeHttpToWebSocketTest
[javatest.batch] 04-12-2022 21:19:08:  TRACE: ** GOT RUN METHOD!
[javatest.batch] 04-12-2022 21:19:08:  TRACE: **runmethod=upgradeHttpToWebSocketTest
[javatest.batch] 04-12-2022 21:19:08:  TRACE: ABOUT TO GET SETUP METHOD!
[javatest.batch] 04-12-2022 21:19:08:  TRACE: No setupMethod annotation present
[javatest.batch] 04-12-2022 21:19:08:  TRACE: getSetupMethod - checking for testcase specific setup method:  upgradeHttpToWebSocketTest_setup
[javatest.batch] 04-12-2022 21:19:08:  TRACE: getSetupMethod - checking for default class specific setup method
[javatest.batch] 04-12-2022 21:19:08:  TRACE: GOT SETUP METHOD!
[javatest.batch] 04-12-2022 21:19:08:  TRACE: No cleanupMethod annotation present
[javatest.batch] 04-12-2022 21:19:08:  TRACE: getCleanupMethod - checking for testcase specific cleanup method:  upgradeHttpToWebSocketTest_cleanup
[javatest.batch] 04-12-2022 21:19:08:  TRACE: getCleanupMethod - checking for default class specific cleanup method
[javatest.batch] 04-12-2022 21:19:08:  TRACE: GOT CLEANUP METHOD!
[javatest.batch] 04-12-2022 21:19:08:  TRACE: ABOUT TO INVOKE SETUP METHOD!
[javatest.batch] 04-12-2022 21:19:08:  TRACE: setup method WebSocketCommonClient
[javatest.batch] 04-12-2022 21:19:08:  [WebSocketCommonClient] Test setup OK
[javatest.batch] 04-12-2022 21:19:08:  TRACE: INVOKED SETUP METHOD!
[javatest.batch] 04-12-2022 21:19:08:  TRACE: ABOUT TO INVOKE EETEST RUN METHOD!
[javatest.batch] 04-12-2022 21:19:09:  [WebSocketCommonClient] Test cleanup OK
[javatest.batch] 04-12-2022 21:19:10:  TRACE: SLEPT FOR:  1000
[javatest.batch] 04-12-2022 21:19:10:  TRACE: in custom vehicle so call on EETest.
[javatest.batch] 04-12-2022 21:19:10:  TRACE: *** in EETest.run(argv,p)
[javatest.batch] 04-12-2022 21:19:10:  TRACE: TESTCLASS=com.sun.ts.tests.websocket.spec.servercontainer.upgradehttptowebsocket.WSClient
[javatest.batch] 04-12-2022 21:19:10:  TRACE: ** IN getRunMethod: testClass=com.sun.ts.tests.websocket.spec.servercontainer.upgradehttptowebsocket.WSClient
[javatest.batch] 04-12-2022 21:19:10:  TRACE: ** IN getRunMethod: testname=upgradeHttpToWebSocketTest
[javatest.batch] 04-12-2022 21:19:10:  TRACE: ** GOT RUN METHOD!
[javatest.batch] 04-12-2022 21:19:10:  TRACE: **runmethod=upgradeHttpToWebSocketTest
[javatest.batch] 04-12-2022 21:19:10:  TRACE: ABOUT TO GET SETUP METHOD!
[javatest.batch] 04-12-2022 21:19:10:  TRACE: No setupMethod annotation present
[javatest.batch] 04-12-2022 21:19:10:  TRACE: getSetupMethod - checking for testcase specific setup method:  upgradeHttpToWebSocketTest_setup
[javatest.batch] 04-12-2022 21:19:10:  TRACE: getSetupMethod - checking for default class specific setup method
[javatest.batch] 04-12-2022 21:19:10:  TRACE: GOT SETUP METHOD!
[javatest.batch] 04-12-2022 21:19:10:  TRACE: No cleanupMethod annotation present
[javatest.batch] 04-12-2022 21:19:10:  TRACE: getCleanupMethod - checking for testcase specific cleanup method:  upgradeHttpToWebSocketTest_cleanup
[javatest.batch] 04-12-2022 21:19:10:  TRACE: getCleanupMethod - checking for default class specific cleanup method
[javatest.batch] 04-12-2022 21:19:10:  TRACE: GOT CLEANUP METHOD!
[javatest.batch] 04-12-2022 21:19:10:  TRACE: ABOUT TO INVOKE SETUP METHOD!
[javatest.batch] 04-12-2022 21:19:10:  TRACE: setup method WebSocketCommonClient
[javatest.batch] 04-12-2022 21:19:10:  [WebSocketCommonClient] Test setup OK
[javatest.batch] 04-12-2022 21:19:10:  TRACE: INVOKED SETUP METHOD!
[javatest.batch] 04-12-2022 21:19:10:  TRACE: ABOUT TO INVOKE EETEST RUN METHOD!
[javatest.batch] 04-12-2022 21:19:10:  ERROR: Received: [TCK upgrade test messageTCK upgrade test message] but should have been [TCK upgrade test message]
[javatest.batch] com.sun.ts.lib.harness.EETest$Fault: Received: [TCK upgrade test messageTCK upgrade test message] but should have been [TCK upgrade test message]
[javatest.batch] 	at com.sun.ts.tests.websocket.spec.servercontainer.upgradehttptowebsocket.WSClient.upgradeHttpToWebSocketTest(WSClient.java:83)
[javatest.batch] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[javatest.batch] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[javatest.batch] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[javatest.batch] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[javatest.batch] 	at com.sun.ts.lib.harness.EETest.run(EETest.java:596)
[javatest.batch] 	at com.sun.ts.lib.harness.ServiceEETest.run(ServiceEETest.java:115)
[javatest.batch] 	at com.sun.ts.lib.harness.EETest.getPropsReady(EETest.java:486)
[javatest.batch] 	at com.sun.ts.lib.harness.ServiceEETest.run(ServiceEETest.java:209)
[javatest.batch] 	at com.sun.ts.tests.websocket.common.client.WebSocketCommonClient.run(WebSocketCommonClient.java:570)
[javatest.batch] 	at com.sun.ts.tests.websocket.spec.servercontainer.upgradehttptowebsocket.WSClient.main(WSClient.java:44)
[javatest.batch] 04-12-2022 21:19:10:  ERROR: Test case throws exception: com.sun.ts.lib.harness.EETest$Fault: Received: [TCK upgrade test messageTCK upgrade test message] but should have been [TCK upgrade test message]
[javatest.batch] 04-12-2022 21:19:10:  ERROR: Exception at:  
[javatest.batch] 04-12-2022 21:19:10:  ERROR: com.sun.ts.lib.harness.EETest$Fault: Received: [TCK upgrade test messageTCK upgrade test message] but should have been [TCK upgrade test message]
[javatest.batch] 	at com.sun.ts.tests.websocket.spec.servercontainer.upgradehttptowebsocket.WSClient.upgradeHttpToWebSocketTest(WSClient.java:83)
[javatest.batch] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[javatest.batch] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[javatest.batch] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[javatest.batch] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[javatest.batch] 	at com.sun.ts.lib.harness.EETest.run(EETest.java:596)
[javatest.batch] 	at com.sun.ts.lib.harness.ServiceEETest.run(ServiceEETest.java:115)
[javatest.batch] 	at com.sun.ts.lib.harness.EETest.getPropsReady(EETest.java:486)
[javatest.batch] 	at com.sun.ts.lib.harness.ServiceEETest.run(ServiceEETest.java:209)
[javatest.batch] 	at com.sun.ts.tests.websocket.common.client.WebSocketCommonClient.run(WebSocketCommonClient.java:570)
[javatest.batch] 	at com.sun.ts.tests.websocket.spec.servercontainer.upgradehttptowebsocket.WSClient.main(WSClient.java:44)
[javatest.batch] 
[javatest.batch] 04-12-2022 21:19:10:  [WebSocketCommonClient] Test cleanup OK
[javatest.batch] 04-12-2022 21:19:11:  TRACE: SLEPT FOR:  1000
[javatest.batch] 04-12-2022 21:19:11:  TRACE: in custom vehicle so call on EETest.
[javatest.batch] 04-12-2022 21:19:11:  TRACE: *** in EETest.run(argv,p)
[javatest.batch] 04-12-2022 21:19:11:  TRACE: TESTCLASS=com.sun.ts.tests.websocket.spec.servercontainer.upgradehttptowebsocket.WSClient
[javatest.batch] 04-12-2022 21:19:11:  TRACE: ** IN getRunMethod: testClass=com.sun.ts.tests.websocket.spec.servercontainer.upgradehttptowebsocket.WSClient
[javatest.batch] 04-12-2022 21:19:11:  TRACE: ** IN getRunMethod: testname=upgradeHttpToWebSocketTest
[javatest.batch] 04-12-2022 21:19:11:  TRACE: ** GOT RUN METHOD!
[javatest.batch] 04-12-2022 21:19:11:  TRACE: **runmethod=upgradeHttpToWebSocketTest
[javatest.batch] 04-12-2022 21:19:11:  TRACE: ABOUT TO GET SETUP METHOD!
[javatest.batch] 04-12-2022 21:19:11:  TRACE: No setupMethod annotation present
[javatest.batch] 04-12-2022 21:19:11:  TRACE: getSetupMethod - checking for testcase specific setup method:  upgradeHttpToWebSocketTest_setup
[javatest.batch] 04-12-2022 21:19:11:  TRACE: getSetupMethod - checking for default class specific setup method
[javatest.batch] 04-12-2022 21:19:11:  TRACE: GOT SETUP METHOD!
[javatest.batch] 04-12-2022 21:19:11:  TRACE: No cleanupMethod annotation present
[javatest.batch] 04-12-2022 21:19:11:  TRACE: getCleanupMethod - checking for testcase specific cleanup method:  upgradeHttpToWebSocketTest_cleanup
[javatest.batch] 04-12-2022 21:19:11:  TRACE: getCleanupMethod - checking for default class specific cleanup method
[javatest.batch] 04-12-2022 21:19:11:  TRACE: GOT CLEANUP METHOD!
[javatest.batch] 04-12-2022 21:19:11:  TRACE: ABOUT TO INVOKE SETUP METHOD!
[javatest.batch] 04-12-2022 21:19:11:  TRACE: setup method WebSocketCommonClient
[javatest.batch] 04-12-2022 21:19:11:  [WebSocketCommonClient] Test setup OK
[javatest.batch] 04-12-2022 21:19:11:  TRACE: INVOKED SETUP METHOD!
[javatest.batch] 04-12-2022 21:19:11:  TRACE: ABOUT TO INVOKE EETEST RUN METHOD!
[javatest.batch] 04-12-2022 21:19:11:  ERROR: Received: [TCK upgrade test messageTCK upgrade test messageTCK upgrade test message] but should have been [TCK upgrade test message]
[javatest.batch] com.sun.ts.lib.harness.EETest$Fault: Received: [TCK upgrade test messageTCK upgrade test messageTCK upgrade test message] but should have been [TCK upgrade test message]
[javatest.batch] 	at com.sun.ts.tests.websocket.spec.servercontainer.upgradehttptowebsocket.WSClient.upgradeHttpToWebSocketTest(WSClient.java:83)
[javatest.batch] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[javatest.batch] 04-12-2022 21:19:11:  ERROR: Test case throws exception: com.sun.ts.lib.harness.EETest$Fault: Received: [TCK upgrade test messageTCK upgrade test messageTCK upgrade test message] but should have been [TCK upgrade test message]
[javatest.batch] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[javatest.batch] 04-12-2022 21:19:11:  ERROR: Exception at:  
[javatest.batch] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[javatest.batch] 04-12-2022 21:19:11:  ERROR: com.sun.ts.lib.harness.EETest$Fault: Received: [TCK upgrade test messageTCK upgrade test messageTCK upgrade test message] but should have been [TCK upgrade test message]
[javatest.batch] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[javatest.batch] 	at com.sun.ts.tests.websocket.spec.servercontainer.upgradehttptowebsocket.WSClient.upgradeHttpToWebSocketTest(WSClient.java:83)
[javatest.batch] 	at com.sun.ts.lib.harness.EETest.run(EETest.java:596)
[javatest.batch] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[javatest.batch] 	at com.sun.ts.lib.harness.ServiceEETest.run(ServiceEETest.java:115)
[javatest.batch] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[javatest.batch] 	at com.sun.ts.lib.harness.EETest.getPropsReady(EETest.java:486)
[javatest.batch] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[javatest.batch] 	at com.sun.ts.lib.harness.ServiceEETest.run(ServiceEETest.java:209)
[javatest.batch] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[javatest.batch] 	at com.sun.ts.tests.websocket.common.client.WebSocketCommonClient.run(WebSocketCommonClient.java:570)
[javatest.batch] 	at com.sun.ts.lib.harness.EETest.run(EETest.java:596)
[javatest.batch] 	at com.sun.ts.tests.websocket.spec.servercontainer.upgradehttptowebsocket.WSClient.main(WSClient.java:44)
[javatest.batch] 	at com.sun.ts.lib.harness.ServiceEETest.run(ServiceEETest.java:115)
[javatest.batch] 	at com.sun.ts.lib.harness.EETest.getPropsReady(EETest.java:486)
[javatest.batch] 	at com.sun.ts.lib.harness.ServiceEETest.run(ServiceEETest.java:209)
[javatest.batch] 	at com.sun.ts.tests.websocket.common.client.WebSocketCommonClient.run(WebSocketCommonClient.java:570)
[javatest.batch] 	at com.sun.ts.tests.websocket.spec.servercontainer.upgradehttptowebsocket.WSClient.main(WSClient.java:44)
[javatest.batch] 
[javatest.batch] 04-12-2022 21:19:11:  [WebSocketCommonClient] Test cleanup OK
[javatest.batch] 04-12-2022 21:19:12:  TRACE: SLEPT FOR:  1000
[javatest.batch] STATUS:Failed.Test case throws exception: com.sun.ts.lib.harness.EETest$Fault: Received: [TCK upgrade test messageTCK upgrade test messageTCK upgrade test message] but should have been [TCK upgrade test message]
[javatest.batch] Failed. Test case throws exception: com.sun.ts.lib.harness.EETest$Fault: Received: [TCK upgrade test messageTCK upgrade test messageTCK upgrade test message] but should have been [TCK upgrade test message]
[javatest.batch] ********************************************************************************
[javatest.batch] Finished Test:  FAILED........com/sun/ts/tests/websocket/spec/servercontainer/upgradehttptowebsocket/WSClient.java#upgradeHttpToWebSocketTest
[javatest.batch] ********************************************************************************
[javatest.batch] Number of tests completed:  1 (0 passed, 1 failed, 0 with errors)

### PR DESCRIPTION
**Pull request by joakime**
**Fixes Issue**

* #926

**Related Issue(s)**

* #926

**Describe the change**

Changes `StringBuffer` to not be static, but per endpoint instance (same for `CountdownLatch`) to make test reliable in multi threaded environment.

Chose not to use `MessageValidator.checkSearchStrings` as that is a substring search, and this needs to be a whole string assertion.

CC @alwin-joseph @anajosep @arjantijms @cesarhernandezgt @dblevins @m0mus @edbratt @gurunrao @jansupol @jgallimore @kazumura @kwsutter @LanceAndersen @bhatpmk @RohitKumarJain @shighbar @gthoman @brideck @scottmarlow @ropalka @markt-asf

### CODE REVIEW

**Comment by scottmarlow** [comment]
I'll start a TCK test on Jenkins CI to run with this change.

**Review by jansupol — APPROVED** [review]
LGTM

**Comment by ropalka** [comment]
LGTM as well

**Comment by scottmarlow** [comment]
@joakime @jansupol should we stage a new Standalone WebSocket TCK with this change?  

CC @gurunrao

**Comment by jansupol** [comment]
I plan to rerun the certification request after the change is restaged.

**Comment by gurunrao** [comment]
@jansupol :  have re-staged the TCK here - https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee10/staged/eftl/
CI run details: https://ci.eclipse.org/jakartaee-tck/job/10/job/eftl-standalonetck-build-run-100/102/testReport/
Promoted TCK to https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee10/promoted/eftl/
CC @scottmarlow @joakime

**Pull request merged**
