### PR TITLE
#627 Class Not Found: JDBC driver org.apache.derby.jdbc.EmbeddedDriver could not be loaded

### PR DESCRIPTION
**Pull request by hussainnm**
Fix derbyEmbedded.classpath to include derbyshared.jar and derbytools.jar

### CODE REVIEW

**Comment by scottmarlow** [comment]
Seems likely that this is needed since org.apache.derby.jdbc.EmbeddedDriver is in the derbytools.jar (used to be in derby.jar)

**Review by scottmarlow — APPROVED** [review]

**Comment by scottmarlow** [comment]
+1 for also adding derbyshared.jar

**Comment by hussainnm** [comment]
Do I need to make the same changes to ts.jte too?

**Review by LanceAndersen — APPROVED** [review]

**Comment by LanceAndersen** [comment]
> Do I need to make the same changes in ts.jte too?

derbyshared.jar is new starting with 10.15.1.3 which was built with OpenJDK 64-Bit Server VM 18.9 (build 11+28, mixed mode).  So if ts.jte is still intended to be used with JDK 8, I would only add a comment to add the jar if 10.15.1.3 is used

**Comment by hussainnm** [comment]
Understood. No changes are required for ts.jte.

**Pull request merged**
