### PR TITLE
Messaging tests for repeatable annotations

### PR DESCRIPTION
**Pull request by OndroMih**
**Fixes Issue**
* https://github.com/jakartaee/messaging/issues/299
* https://github.com/jakartaee/messaging/issues/300

**Related Issue(s)**

**Describe the change**
Removed the wrapper annotations in existing tests and use repeatable annotations @JMSDestinationDefinition @JMSConnectionFactoryDefinition directly

**Additional context**
Also applied formatting from commit https://github.com/eclipse-ee4j/jakartaee-tck/commit/6169ab96570a25023d88239fbbfb8769672b4bed to the original .src files, which overwrite the *.java files during TCK build which were formatted by that commit.

To see the main change without formatting changes, checkout the first commit https://github.com/eclipse-ee4j/jakartaee-tck/commit/5ecd8750afb6ac690a644da85771cec8416bd4b3

I've verified that the tests are OK by compiling and running the Jakarta EE TCK against GF 7 (I built the whole TCK but only executed the modified tests). The tests passed after I added the [Jakarta EE 10 schemas](https://github.com/eclipse-ee4j/glassfish/pull/23812) to GF 7 milestone build. No change is required in the Messaging implementations to support the repeatable annotations.

CC @alwin-joseph @anajosep @arjantijms @cesarhernandezgt @dblevins @m0mus @edbratt @gurunrao @jansupol @jgallimore @kazumura @kwsutter @LanceAndersen @bhatpmk @RohitKumarJain @shighbar @gthoman @brideck @scottmarlow

### CODE REVIEW

**Comment by pzygielo** [comment]
Just to few questions and observations.

> I've verified that the tests are OK by compiling and running the Jakarta EE TCK against GF 7 (I built the whole TCK but only executed the modified tests). 
> The tests passed after I added the [Jakarta EE 10 schemas](https://github.com/eclipse-ee4j/glassfish/pull/23812) to GF 7 milestone build. 
> No change is required in the Messaging implementations to support the repeatable annotations.

- Implementation at least has to deliver new API.

- Would those UNMODIFIED tests pass with upcoming JMS 3.1? (With the meaning - shouldn't jms-api be updated in first place?)

- What `jakarta.jms-api` version was used for testing? with 3.0 I'm geeting `JMSDestinationDefinition is not a repeatable annotation type` compilation error. I suppose jms-api jar was also replaced, wasn't it? Description doesn't mention that.

- I was under impression that `20` in `ee20` is for spec version. Shouldn't 3.1 feature deserve new set of tests?

- unused imports
  - https://github.com/eclipse-ee4j/jakartaee-tck/blob/550a60fae3f3044c94ba1ea94808f7abf1373fbe/src/com/sun/ts/tests/jms/ee20/resourcedefs/annotations/Client.java#L33
  - https://github.com/eclipse-ee4j/jakartaee-tck/blob/550a60fae3f3044c94ba1ea94808f7abf1373fbe/src/com/sun/ts/tests/jms/ee20/resourcedefs/annotations/Client.java#L37
  
- messages not updated - they still reference `*Definitions`

Maybe messaging could stage RC build?

**Comment by OndroMih** [comment]
All are good questions, @pzygielo. 

You're right, I also dropped the new `jakarta.jms-api.jar` version into GlassFish, into the `modules` directory. I built it from sources but soon I plan to release . I'll update the description. What I meant is that implementation itself and doesn't have to be updated because the change only impacts the API. 

GlassFish needs to contain the new API but I think that OpenMQ doesn't have to be updated. Maybe I'm wrong though, I don't know the details of OpenMQ integration in GlassFish. I only know that the API doesn't impact Java SE and thus the standalone TCK doesn't cover it so I assume that OpenMQ doesn't need any update to become CI for Messaging 3.1.

I haven't worked with Jakarta EE TCK before and this is my first attempt, so I tried to do things as simple as possible. That's why I only modified existing tests and didn't create new ones for ee3.1. I can try to refactor it, leave the ee20 tests untouched and create a new test for ee3.1 if I have enough time. But we only have 1 week to release prepare all for release review.

**Comment by scottmarlow** [comment]
Building Platform TCK via https://ci.eclipse.org/jakartaee-tck/job/jakartaee-tck-scottmarlow/job/OndroMih-jms-299-300-tests-repeated-annotations/1 with this pull request

**Comment by OndroMih** [comment]
It's expected that the TCK still fails with GlassFish and OpenMQ.

That TCK job against GlassFish 7 is failing on "schema is not found" because it runs against outdated GF build. The build at https://download.eclipse.org/ee4j/glassfish/glassfish-7.0.0-SNAPSHOT-nightly.zip is not being generated because of an error in the build script: https://ci.eclipse.org/glassfish/view/GlassFish/job/glassfish_build-and-publish-to-eclipse-download/648/console. The schemas are already updated with https://github.com/eclipse-ee4j/glassfish/pull/23816 in the glassfish master. I've contacted the GF team to fix the script.

GF and OpenMQ have not integrated the snapshot Messaging API artifact. I'm working on releasing the API artifact to a staging repository so that it can be easily integrated.

**Comment by scottmarlow** [comment]
Perhaps the tests that now use Repeatable annotations should have an assertionID that refers to the java.lang.annotation.Repeatable used in jakarta.jms.JMSConnectionFactoryDefinition + jakarta.jms.JMSDestinationDefinition, as some Messaging implementations may need to understand why they are getting TCK test failures due to their implementation not yet implementing Repeatable annotation use in application deployments.

Some contributors like to [regenerate the assertionIDs](https://github.com/eclipse-ee4j/jakartaee-tck/wiki/Steps-to-generate-the-html-version-of-the-SpecAssertions.xml).  Others might just manually update the assertionID files in the Platform TCK.  

Some [background on assertionIDS is here](https://github.com/eclipse-ee4j/jakartaee-tck/wiki/Guide-to-adding-Specification-Assertions).

**Comment by alwin-joseph** [comment]
I have verified that JMS tests passes when run against https://jakarta.oss.sonatype.org/content/repositories/staging/org/glassfish/main/distributions/glassfish/7.0.0-M2/glassfish-7.0.0-M2.zip .

But I was expecting metadata test failures as I had not included https://github.com/eclipse-ee4j/jakartaee-tck/pull/825 in my test run. The jms version obtained is still 3.0 despite https://github.com/eclipse-ee4j/glassfish/commit/80c0661a043b390e48e2d39a2f7d2255e9d54131 was made. I will verify those tests later.

Merging this now.

**Review by alwin-joseph — APPROVED** [review]
LGTM

**Comment by pzygielo** [comment]
> But I was expecting metadata test failures as I had not included #825 in my test run. The jms version obtained is still 3.0 despite [eclipse-ee4j/glassfish@80c0661](https://github.com/eclipse-ee4j/glassfish/commit/80c0661a043b390e48e2d39a2f7d2255e9d54131) was made. I will verify those tests later.

If the version is reported from OpenMQ - GF700M2 has OpenMQ with JMS30 still.

**Pull request merged**
