### PR TITLE
Add servlet3 folder to the Jakarta REST TCK bundle.

### LINKED ISSUE #615: For Jakarta EE 9.1, add jaxrs/servlet3 folder back to the TCK
In Java EE / Jakarta EE 8 the [servlet3](https://github.com/eclipse-ee4j/jakartaee-tck/tree/master/src/com/sun/ts/tests/jaxrs/servlet3) folder was not part of the TCK, since hypothetically a JAX-RS implementation could be built atop Servlet 2.5 container. The TCK tests use servlet 2.5 descriptors, whereas the `servlet3` folder contains tests that use Servlet 3 autodiscovery mechanism.

In Jakarta EE 9+, Jakarta Servlet 5.0 is required, so the tests can be part of the Standalone TCK bundle.

### PR DESCRIPTION
**Pull request by jansupol**
Signed-off-by: jansupol <jan.supol@oracle.com>

Fixes #615.

### CODE REVIEW

**Review by gurunrao — APPROVED** [review]
LGTM

**Review by stuartwdouglas — APPROVED** [review]

**Review by spericas — APPROVED** [review]

**Comment by scottmarlow** [comment]
I think that this needs a test run with GlassFish, Tomee, OpenLiberty, WildFly before merging.  As part of the GlassFish testing with this change, we would generate a 9.1 Platform TCK that could be used for testing.  We probably could also generate a Standalone JAXRS TCK for others to test with.

**Comment by jansupol** [comment]
@scottmarlow The tests were already as part of Jakarta EE 9 TCK. Running with full application servers as you request does not make any change; GlassFish, Tomee, OpenLiberty, WildFly support the full Jakarta EE platform and all the Jakarta EE 9 TCK tests would pass if added to the TCK bundle. The possible issue is for (possible) technologies that do implement only a Standalone part of the Spec. Or do I miss something?

**Comment by scottmarlow** [comment]
> @scottmarlow The tests were already as part of Jakarta EE 9 TCK. Running with full application servers as you request does not make any change; GlassFish, Tomee, OpenLiberty, WildFly support the full Jakarta EE platform and all the Jakarta EE 9 TCK tests would pass if added to the TCK bundle. The possible issue is for (possible) technologies that do implement only a Standalone part of the Spec. Or do I miss something?

Thanks for explaining.

**Comment by scottmarlow** [comment]
https://ci.eclipse.org/jakartaee-tck/job/9.1/job/eftl-standalonetck-build-run-910/52 will build and test with this change.

**Pull request merged**
