### PR TITLE
start building  with staged EE 10 SPEC APIs

### PR DESCRIPTION
**Pull request by scottmarlow**
Signed-off-by: Scott Marlow <smarlow@redhat.com>

Adds the staging repo via added parent pom + updates to [currently available staged SPEC API versions](https://jakarta.oss.sonatype.org/content/repositories/staging).  Note that some SPEC APIs may be merged into `Jakarta XML Web Services 4.0` (like Soap Attachments + Jakarta Web Services Metadata 3.0).  

More changes are needed to deal with the technologies merged to https://jakarta.ee/specifications/xml-web-services/4.0 (with regard to building standalone TCKs).

### CODE REVIEW

**Review by gurunrao — COMMENTED** [review]
similar changes will be required for standalone tck build script - https://github.com/eclipse-ee4j/jakartaee-tck/blob/master/docker/build_standalone-tcks.sh, to build from staged ee 10 SPEC API.

**Comment by scottmarlow** [comment]
FYI, tracking issue is https://github.com/eclipse-ee4j/jakartaee-tck/issues/756

**Comment by scottmarlow** [comment]
[JACC Standalone TCK tests are now passing](https://ci.eclipse.org/jakartaee-tck/job/jakartaee-tck-scottmarlow/job/add_staged_specapi/12/testReport.

[Just started a Full Platform TCK build/run.](https://ci.eclipse.org/jakartaee-tck/job/jakartaee-tck-scottmarlow/job/add_staged_specapi/13/)

**Comment by scottmarlow** [comment]
I'm doing more testing of the Standalone TCKs but I think they will all pass via https://ci.eclipse.org/jakartaee-tck/job/jakartaee-tck-scottmarlow/job/add_staged_specapi/20 (verified that jaxrs passed yesterday which was the only one failing due to build failures that are now resolved).

Locally, I tried running the Platform TCK build from yesterday (https://ci.eclipse.org/jakartaee-tck/job/jakartaee-tck-scottmarlow/job/add_staged_specapi/19/artifact/jakartaeetck-bundles/jakartaeetck-10.0.0.zip).   I am locally running the jaxrs tests and they seem to be passing fine with WildFly (master branch):
```
[javatest.batch] ********************************************************************************$
[javatest.batch] Finished Test:  PASSED........com/sun/ts/tests/jaxrs/ee/rs/formparam/sub/JAXRSSubClient.java#nonDefaultFormParamValueOfTest_from_standalone$
[javatest.batch] ********************************************************************************$
[javatest.batch] Number of tests completed:  1875 (1875 passed, 0 failed, 0 with errors)$
[javatest.batch] Number of tests remaining:  990$
```

While with https://download.eclipse.org/ee4j/glassfish/glassfish-6.1.0.zip on JDK11 testing, we fail with:
```
A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.StackOverflowError
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:315)
```

I'm guessing the java.lang.StackOverflowError is a configuration failure but not really sure.

**Review by gurunrao — APPROVED** [review]

**Comment by scottmarlow** [comment]
Thanks for the review @gurunrao !

**Pull request merged**
