### PR TITLE
Make sure TSSV Logger gets initialized when using an external ACF

### PR DESCRIPTION
**Pull request by jeanouii**
Signed-off-by: Jean-Louis Monteiro <jlmonteiro@tomitribe.com>

This PR fixes another bad initialization of the TSSV Logger that allow post assertions in the tests.
The logger gets intialized too late and we loose some records.

### CODE REVIEW

**Comment by gurunrao** [comment]
started testing PR with GF 6.1 and JDK 11, we have minor build issue. I will complete test post fix for build is merged.
CI build + run - https://ci.eclipse.org/jakartaee-tck/job/guru/job/jakartaeetck-gtest/job/authentication-fix/

**Review by gurunrao — APPROVED** [review]
PR passes GF 6.1 + JDK 11
Standalone TCK run - https://ci.eclipse.org/jakartaee-tck/job/guru/job/jakartaeetck-gtest/job/authentication-fix/5/ 
Platform TCK run - https://ci.eclipse.org/jakartaee-tck/job/guru/job/jakartaeetck-gtest/job/authentication-fix/4/
changes LGTM

**Comment by scottmarlow** [comment]
@arjantijms can you please approve?

**Comment by jeanouii** [comment]
Any update?

@arjantijms 
@scottmarlow 

It's a small fix and would allow TomEE to move on with coverage

**Comment by scottmarlow** [comment]
By lazy consensus this change is considered accepted and will be merged.

**Comment by arjantijms** [comment]
I thought it was already approved, but +1 from me

**Pull request merged**
