### PR TITLE
This PR is for Issue#124

### PR DESCRIPTION
**Pull request by RohitKumarJain**
raising this PR for issue https://github.com/eclipse-ee4j/jakartaee-tck/issues/124 .

### CODE REVIEW

**Comment by chengfang** [comment]
We also need to apply the same fix to `com/sun/ts/tests/ejb32/lite/timer/schedule/lifecycle`

**Comment by scottmarlow** [comment]
We started merging some javax => jakarta class namespace changes yesterday, include [ejb test sources](https://github.com/eclipse-ee4j/jakartaee-tck/pull/170).  The TCK repo is now in transition, don't bother addressing the conflicts yet, as things are still changing.  We should have a window to merge this later once we finish switching to jakarta namespace.

Please do let me know if you see anything wrong in [jakartaee-tck/pull/170](https://github.com/eclipse-ee4j/jakartaee-tck/pull/170).  IMO, it is too big to review but if someone is good at quickly reviewing large diffs, please do use your skills and we can make changes as needed!

**Comment by RohitKumarJain** [comment]
> We also need to apply the same fix to `com/sun/ts/tests/ejb32/lite/timer/schedule/lifecycle`

Yes, we can apply the same fix for "`com/sun/ts/tests/ejb32/lite/timer/schedule/lifecycle`". Would you like to raise another bug to apply the changes in `com/sun/ts/tests/ejb32/lite/timer/schedule/lifecycle` as this issue primarily raised for ejb30 or if you ok, for me to make changes in this PR?

**Comment by chengfang** [comment]
I think it's easier to fix both directories within the same bug and PR. @RohitKumarJain yes, please update the PR to include the other directory if you don't mind.

**Pull request merged**
