### PR TITLE
Reverts #349 and address root cause of JSP test failure #536 and also removes ELJspVersionTag test

### PR DESCRIPTION
**Pull request by scottmarlow**
This is for testing removal of com.sun.ts.tests.jsp.spec.el.jsp.ELJspVersionTag (https://github.com/eclipse-ee4j/jakartaee-tck/pull/536 which is included in this pr so we can do it all together in one git push to master).  I'll first run the JSP tests in Platform TCK to verify that the remaining JSP tests still pass.  

@markt-asf Any preferences for what we tag the commit as?  How about `ELJspVersionTag`? or `removed_ELJspVersionTag`?

### CODE REVIEW

**Comment by scottmarlow** [comment]
Testing JSP tests via https://ci.eclipse.org/jakartaee-tck/job/jakartaee-tck-scottmarlow/job/markt-asf-issue-535_marlow_2/2/

**Comment by scottmarlow** [comment]
The JSP tests passed on  https://ci.eclipse.org/jakartaee-tck/job/jakartaee-tck-scottmarlow/job/markt-asf-issue-535_marlow_2/2!

**Comment by scottmarlow** [comment]
@markt-asf once this is merged in and commit tagged, I think we will be ready to promote or stage a new JSP TCK with this change.

CC @alwin-joseph

**Review by RohitKumarJain — APPROVED** [review]
LGTM

**Review by gurunrao — APPROVED** [review]

**Comment by scottmarlow** [comment]
Thanks @gurunrao , I'll push a tag now for this commit called `removed_ELJspVersionTag`

**Comment by scottmarlow** [comment]
https://github.com/eclipse-ee4j/jakartaee-tck/releases/tag/removed_ELJspVersionTag is the tag

**Pull request merged**
