### PR TITLE
javax.jms to jakarta.jms

### LINKED ISSUE #221: javax.jms => jakarta.jms
Search and replace to update javax namespace class references for jsm.

Email thread:
https://www.eclipse.org/lists/jakartaee-tck-dev/msg00407.html

### PR DESCRIPTION
**Pull request by cesarhernandezgt**
fix #221

### CODE REVIEW

**Comment by scottmarlow** [comment]
I started reviewing this a few times now, got interrupted by github ui jumping around, not sure why.  Looking on my local machine instead.

**Comment by scottmarlow** [comment]
@cesarhernandezgt after I'm done reviewing the current changes, could you please update the Copyright dates?  

Lately, for already committed changes, I would generate a script on a different branch, so something like:
```
git checkout -b NewTempBranch
# verify that git log shows your change as first commit
git log
# un-commit your change
git reset --soft HEAD~;git reset
# doing "git status" should show all of your modified files now
# generate /tmp/script.sh
rm -f /tmp/script.sh
#echo '#!/bin/sh' > /tmp/script.sh
repo=~/.m2/repository/org/glassfish/copyright/glassfish-copyright-maven-plugin
v=`ls $repo | grep '^[1-9]' | tail -1`
for i in `git status  --porcelain --untracked-files=no | cut -d' ' -f3`; do echo java -cp $repo/$v/glassfish-copyright-maven-plugin-$v.jar org.glassfish.copyright.Copyright -r -c $i >> /tmp/script.sh; done
chmod +x /tmp/script.sh

# commit the files again, or git stash (discard them)
git commit -a -m"you can delete the NewTempBranch branch anyway"
# switch back to the branch for this pull request
git checkout cesarhernandezgt
# review the contents of /tmp/script.sh to verify it is correct for your OS
# mine contains lines like:
# java -cp /home/smarlow/.m2/repository/org/glassfish/copyright/glassfish-copyright-maven-plugin/2.4-SNAPSHOT/glassfish-copyright-maven-plugin-2.4-SNAPSHOT.jar org.glassfish.copyright.Copyright -r -c src/com/sun/ts/tests/appclient/deploy/metadatacomplete/testapp/TestAppClient.java
# run the /tmp/script.sh to update the Copyright dates only in the files that you have already modified
. /tmp/script.sh
# then commit these Copyright date changes as a second signed commit and push that.
```

Scott

**Comment by scottmarlow** [comment]
Hi @cesarhernandezgt, other than the missing Copyright date updates (as mentioned above), this change looks good.

When you update the Copyright date, the Eclipse recommendation is to keep the earliest date mentioned and update the second date (if there is one), to current year (2020), so something like:
```
Copyright (c) 2007, 2020
```
The glassfish-copyright-maven-plugin should handle the needed changes.  Please do create a separate signed commit.

Thanks very much for this very big change!

Scott

**Comment by cesarhernandezgt** [comment]
> Hi @cesarhernandezgt, other than the missing Copyright date updates (as mentioned above), this change looks good.
> 
> When you update the Copyright date, the Eclipse recommendation is to keep the earliest date mentioned and update the second date (if there is one), to current year (2020), so something like:
> 
> ```
> Copyright (c) 2007, 2020
> ```
> 
> The glassfish-copyright-maven-plugin should handle the needed changes. Please do create a separate signed commit.
> 
> Thanks very much for this very big change!
> 
> Scott

Thank you for the feedback. Copyrights were fixed in e37c0fc

**Comment by scottmarlow** [comment]
Hi @cesarhernandezgt I hit this a few times myself, the Copyright date change to lib/dtds/application-client_1_3.dtd should be reverted, as the existing Copyright notice can not be modified.

Same for:
lib/dtds/connector_1_5.dtd
lib/dtds/connector_1_6.dtd
lib/dtds/ejb-jar_2_0.dtd
lib/dtds/sun-server_1_0.dtd
lib/dtds/web-app_2_3.dtd

I'll update this comment, as there are more and I need to change how I am identifying which changes exactly.

Also see [glassfish-copyright-plugin/issues/9](https://github.com/eclipse-ee4j/glassfish-copyright-plugin/issues/9).

**Pull request merged**
