### PR TITLE
Remove security api tck sources and related contents

### PR DESCRIPTION
**Pull request by alwin-joseph**
**Related Issue(s)**
https://github.com/jakartaee/security/issues/219 
https://github.com/jakartaee/security/pull/230
https://github.com/jakartaee/security/pull/226

**Describe the change**
This change removes the security TCK and related contents as they were migrated to Security API repository via https://github.com/jakartaee/security/pull/230

Pending :  The userguide and other docs are yet to be migrated but included to be removed in this PR. Those will be migrated in separate PRs to jakartaee/security repository.

Update : Userguide is migrated in PR https://github.com/jakartaee/security/pull/233

@scottmarlow @gurunrao @arjantijms

### CODE REVIEW

**Review by scottmarlow — COMMENTED** [review]
I reviewed this pull request and the changes are correct.  I am not approving for merging yet though as the new https://github.com/jakartaee/security TCK needs at least one implementation to pass with it.

**Comment by gurunrao** [comment]
we will have to remove https://github.com/eclipse-ee4j/jakartaee-tck/tree/master/src/com/sun/ts/tests/signaturetest/securityapi too, since that logic is used just by securityapi TCK.

**Comment by arjantijms** [comment]
@scottmarlow @alwin-joseph 

GlassFish 7.0.0-M4 passes all the tests in the transferred code. Here it's being run as part of the new TCK:

https://ci.eclipse.org/es/job/1_security-tck-build-and-stage/6/console

```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Jakarta Security TCK - main 3.0.0:
[INFO] 
[INFO] Jakarta Security TCK - main ........................ SUCCESS [ 13.313 s]
[INFO] common ............................................. SUCCESS [ 11.135 s]
[INFO] app-securitycontext ................................ SUCCESS [ 28.580 s]
[INFO] app-securitycontext-auth ........................... SUCCESS [ 24.089 s]
[INFO] app-securitycontext-customprincipal ................ SUCCESS [ 25.410 s]
[INFO] app-mem ............................................ SUCCESS [ 24.503 s]
[INFO] app-db ............................................. SUCCESS [ 28.245 s]
[INFO] app-ldap ........................................... SUCCESS [ 26.450 s]
[INFO] app-ldap2 .......................................... SUCCESS [ 26.856 s]
[INFO] app-ldap3 .......................................... SUCCESS [ 26.429 s]
[INFO] app-custom ......................................... SUCCESS [ 24.785 s]
[INFO] app-multiple-store ................................. SUCCESS [ 24.424 s]
[INFO] app-multiple-store-backup .......................... SUCCESS [ 24.633 s]
[INFO] app-openid ......................................... SUCCESS [ 36.963 s]
[INFO] app-openid2 ........................................ SUCCESS [ 50.189 s]
[INFO] app-openid3 ........................................ SUCCESS [ 45.385 s]
[INFO] app-mem-basic ...................................... SUCCESS [ 25.763 s]
[INFO] app-mem-basic-decorate ............................. SUCCESS [ 24.238 s]
[INFO] app-mem-form ....................................... SUCCESS [ 27.993 s]
[INFO] app-mem-customform ................................. SUCCESS [ 28.463 s]
[INFO] app-custom-session ................................. SUCCESS [ 26.255 s]
[INFO] app-custom-rememberme .............................. SUCCESS [ 32.842 s]
[INFO] app-custom-identity-store-handler .................. SUCCESS [ 28.270 s]
[INFO] app-jaxrs .......................................... SUCCESS [ 25.788 s]
[INFO] Old Jakarta Security TCK - build ................... SUCCESS [02:36 min]
[INFO] Old Jakarta Security TCK - main .................... SUCCESS [  1.539 s]
[INFO] Old Jakarta Security TCK - run ..................... SUCCESS [06:07 min]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  19:47 min
[INFO] Finished at: 2022-04-24T17:00:03Z
[INFO] ------------------------------------------------------------------------
```

and

```
[INFO]      [exec] [javatest.batch] ********************************************************************************
[INFO]      [exec] [javatest.batch] Completed running 84 tests.
[INFO]      [exec] [javatest.batch] Number of Tests Passed      = 84
[INFO]      [exec] [javatest.batch] Number of Tests Failed      = 0
[INFO]      [exec] [javatest.batch] Number of Tests with Errors = 0
[INFO]      [exec] [javatest.batch] ********************************************************************************
```

**Review by arjantijms — APPROVED** [review]

**Comment by alwin-joseph** [comment]
Below is the checklist that needs to be completed.

- [ ] Platform TCK pull request is needed to eliminate any Platform TCK tests not needed to validate Platform SPEC requirements. 
- [ ] Send email to [Platform](https://accounts.eclipse.org/mailing-list/jakartaee-platform-dev), [Platform TCK](https://accounts.eclipse.org/mailing-list/jakartaee-tck-dev), relevant SPEC API mailing lists with PR link for removing duplicate tests.
- [ ] Ensure that some validation of SPEC API is done for each tested EE container/vehicle.
- [ ] Review each test and make a determination if there is a specific Platform requirement being tested beyond just using any parts of SPEC API in specified containers.
- [ ] If the new SPEC API TCK validates the Platform requirements (with required EE container/vehicles), all of the Platform TCK tests specific to that SPEC API may be removed.

The Platform requirement is spelled out in [Platform 9.1 Specification section](https://jakarta.ee/specifications/platform/9.1/jakarta-platform-spec-9.1.html#a2741)

**Comment by gurunrao** [comment]
if there are no pending items for the PR, lets merge the PR today EOD.

**Review by gurunrao — APPROVED** [review]

**Pull request merged**
