### PR TITLE
remove jsonp tck.

### PR DESCRIPTION
**Pull request by gurunrao**
remove jsonp standalone tck scripts, tests from jakarta ee TCK repository. 
As per discussion pluggability tests, signature test and 4 tests will be run as part of platform TCK for jsonp test-suite.
PR.
PR also removes jsonp user-guide, which has been migrated to https://github.com/eclipse-ee4j/jsonp/tree/master/tck/tck-docs.
CI run - https://ci.eclipse.org/jakartaee-tck/job/guru/job/jakartaee-tck-build-run/job/jsonp-remove/10/

Signed-off-by: gurunrao <gurunandan.rao@oracle.com>

### CODE REVIEW

**Comment by gurunrao** [comment]
https://github.com/eclipse-ee4j/jakartaee-platform/wiki/Guidelines_For_Standalone_TCKs describes process around removing duplicate TCK tests from the Platform TCK.  

Note that we intend to remove the `The pull request will remain open during the discussion period of two weeks.` from the ^ wiki, as was discussed in [this week's Platform call](https://github.com/eclipse-ee4j/jakartaee-platform/pull/466/files#diff-7d9a41b74230eebcf6f63f605093b8022cab1ded8d8ca2f10cb9ae0cb058264eR44).

- [x] Platform TCK pull request is needed to eliminate any Platform TCK tests not needed to validate Platform SPEC requirements. 
- [x] Send email to [Platform](https://accounts.eclipse.org/mailing-list/jakartaee-platform-dev), [Platform TCK](https://accounts.eclipse.org/mailing-list/jakartaee-tck-dev), relevant SPEC API mailing lists with PR link for removing duplicate tests.
- [ ] Ensure that some validation of SPEC API is done for each tested EE container/vehicle.
- [ ] Review each test and make a determination if there is a specific Platform requirement being tested beyond just using any parts of SPEC API in specified containers.
- [ ] If the new SPEC API TCK validates the Platform requirements (with required EE container/vehicles), all of the Platform TCK tests specific to that SPEC API may be removed.

**Review by lukasj — APPROVED** [review]
LGTM

**Comment by gurunrao** [comment]
@scottmarlow - PR is open for 29 days, should we wait for more comments?

**Comment by scottmarlow** [comment]
> @scottmarlow - PR is open for 29 days, should we wait for more comments?

Looking at this now...

**Comment by scottmarlow** [comment]
This looks ready to merge.

**Pull request merged**
