### PR TITLE
Correct number of ~ and ^ characters below updated titles

### PR DESCRIPTION
**Pull request by pzygielo**
**Fixes Issue**
- #1040

**Related Issue(s)**
Specify any related issue(s) links.

**Describe the change**
A clear and concise description of the change.

**Additional context**

CC @alwin-joseph @anajosep @arjantijms @cesarhernandezgt @dblevins @m0mus @edbratt @gurunrao @jansupol @jgallimore @kazumura @kwsutter @LanceAndersen @bhatpmk @RohitKumarJain @shighbar @gthoman @brideck @scottmarlow

### CODE REVIEW

**Comment by scottmarlow** [comment]
Other than the change from `10` to `10.0`, the pr looked good (although I didn't finish reading it).  Thanks for the contribution even though you removed it, I still appreciate the effort and how your changes ensured all titles had the correct number of characters under it.

**Comment by pzygielo** [comment]
Thanks for checking @scottmarlow. 

I'll rebase my changes on current master.

I also have to understand how
> Other than the change from 10 to 10.0

found its (surprising) way to the commit.

**Comment by scottmarlow** [comment]
> > Other than the change from 10 to 10.0
> 
> found its (surprising) way to the commit.

The previous values used on that line were:
- `8` for Jakarta EE 8
- `9` for Jakarta EE 9
- `9.1` for Jakarta EE 9.1

**Comment by pzygielo** [comment]
> I also have to understand how
> 
> > Other than the change from 10 to 10.0
> 
> found its (surprising) way to the commit.

After `mvn package` there are some changes made to the `user_guides/jakartaee/src/main/jbake/content/toc.adoc`:
```diff
diff --git a/user_guides/jakartaee/src/main/jbake/content/toc.adoc b/user_guides/jakartaee/src/main/jbake/content/toc.adoc
index b8b5b72dd..993f815c5 100644
--- a/user_guides/jakartaee/src/main/jbake/content/toc.adoc
+++ b/user_guides/jakartaee/src/main/jbake/content/toc.adoc
@@ -4,7 +4,7 @@ title=Jakarta EE Platform, Enterprise Edition 10 Test Compatibility Kit User's G
 next=title.html
 ~~~~~~
 Jakarta EE Platform, Enterprise Edition 10 Test Compatibility Kit User's Guide, Release 10 for Jakarta EE
-===========================================================================================================
+=========================================================================================================
 
 [[contents]]
 Contents
@@ -40,8 +40,8 @@ link:intro.html#GBFOW[1 Introduction]
 ** link:intro.html#GEVCL[1.5 Additional Jakarta EE 10 Platform TCK Requirements]
 ** link:intro.html#GBFQW[1.6 Getting Started With the Jakarta EE 10 Platform TCK Test Suite]
 
-link:rules.html#GBFSN[2 Procedure for Jakarta Platform, Enterprise Edition 10 Certification]
-~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+link:rules.html#GBFSN[2 Procedure for Jakarta Platform, Enterprise Edition 10.0 Certification]
+~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 
 ** link:rules.html#CJACEHEF[2.1 Certification Overview]
 ** link:rules.html#CJAJFCJI[2.2 Compatibility Requirements]
@@ -51,11 +51,12 @@ link:rules.html#GBFSN[2 Procedure for Jakarta Platform, Enterprise Edition 10 Ce
 *** link:rules.html#[2.3.1 Valid Challenges]
 *** link:rules.html#[2.3.2 Invalid Challenges]
 *** link:rules.html#CJAJEAEI[2.3.3 TCK Test Appeals Steps]
-** link:rules.html#CJAHFAJE[2.4 Specifications for Jakarta Platform, Enterprise Edition Version 10]
-** link:rules.html#CJAHIGAB[2.5 Libraries for Jakarta Platform, Enterprise Edition Version 10]
+** link:rules.html#CJAHFAJE[2.4 Specifications for Jakarta Platform, Enterprise Edition Version 10.0]
+** link:rules.html#CJAHIGAB[2.5 Libraries for Jakarta Platform, Enterprise Edition Version 10.0]
 
+[[procedure-for-jakarta-platform-enterprise-edition-10-web-profile-certification]]
 link:rules-wp.html#GJJPZ[3 Procedure for Jakarta Platform, Enterprise Edition 10 Web Profile Certification]
-~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 
 ** link:rules-wp.html#CEGEJDGE[3.1 Certification Overview]
 ** link:rules-wp.html#CEGFGHIC[3.2 Compatibility Requirements]
@@ -111,8 +112,9 @@ link:config.html#GBFVV[5 Setup and Configuration]
 *** link:config.html#GEYNM[5.5.1 Basic Configuration Overview]
 *** link:config.html#GEYOD[5.5.2 The Configuration Interview]
 
+[[setup-and-configuration-for-testing-with-the-jakarta-ee-10-web-profile]]
 link:webprofileconfig.html#GJRHB[6 Setup and Configuration for Testing with the Jakarta EE 10 Web Profile]
-~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 
 ** link:webprofileconfig.html#GLSEL[6.1 Configuring the Jakarta EE 10 Web Profile Test Environment]
 *** link:webprofileconfig.html#GJWED[6.1.1 To Run Tests Against a Jakarta EE 10 Web Profile Implementation]
```

It seems to be the effect of synchronization with
https://github.com/eclipse-ee4j/jakartaee-tck/blob/e3c22fb40974d210378c50cb1207c5f0c616ec20/user_guides/jakartaee/src/main/jbake/content/rules.adoc#L3 and others there -- as, even without my change, it is rendered as
tck1
tck2
anyway.

Thus if
> Other than the change from 10 to 10.0

is wrong thing to do - I guess `.0` could be removed from the *rules* chapter as well.

**Comment by pzygielo** [comment]
Resubmitted as
- #1046

**Pull request closed without merging**
