### PR TITLE
Optimize imports with Eclipse IDE to remove unused test imports

### PR DESCRIPTION
**Pull request by scottmarlow**
Eliminated the unused Java imports in support of running the https://gist.github.com/scottmarlow/d4a13d15e7c0ea83d35004445b4b84f0 script to product the https://gist.github.com/scottmarlow/0e31e5256507ad0e5c78b3f274d8d4a7 output that shows the per (Jakarta EE Platform TCK) test group dependencies and number of Platform SPEC assertions as well (per test group).

### CODE REVIEW

**Comment by scottmarlow** [comment]
https://ci.eclipse.org/jakartaee-tck/job/jakartaee-tck-scottmarlow/job/optimize_imports_eclipse/1/testReport/ had some test failures that need to be looked into.

**Comment by scottmarlow** [comment]
Somehow `import jakarta.security.auth.message.MessageInfo` got updated to `import com.sun.nio.sctp.MessageInfo`

**Comment by alwin-joseph** [comment]
> https://ci.eclipse.org/jakartaee-tck/job/jakartaee-tck-scottmarlow/job/optimize_imports_eclipse/1/testReport/ had some test failures that need to be looked into.

I see the build has failures in this run. One of the causes is "import com.sun.jmx.mbeanserver.Repository.RegistrationContext" missing?

**Comment by scottmarlow** [comment]
thanks @alwin-joseph , I'll revert the removal of that.  I added the Jakarta SPEC API jar to my Eclipse IDE project but I suspect the project still is missing classes like the com.sun.jmx.mbeanserver.Repository.RegistrationContext dependency.

**Comment by scottmarlow** [comment]
> thanks @alwin-joseph , I'll revert the removal of that. I added the Jakarta SPEC API jar to my Eclipse IDE project but I suspect the project still is missing classes like the com.sun.jmx.mbeanserver.Repository.RegistrationContext dependency.

From searching the build logs for `Compile failed;` found some missing imports on PortableRemoteObject + org.apache.tools.ant.util.StringUtils.  I'll push these changes and try again.  

I didn't see any references to com.sun.jmx.mbeanserver.Repository.RegistrationContext or RegistrationContext in the `build_jakartaeetck.log`.

**Comment by scottmarlow** [comment]
I started https://ci.eclipse.org/jakartaee-tck/job/jakartaee-tck-scottmarlow/job/optimize_imports_eclipse/4/testReport/ this morning after addressing some of the missing imports.  

I'll look in the build log after for more `Compile failed;` failures.

**Comment by scottmarlow** [comment]
> Compile failed;

I see the compile failure for webservices now.  Looks like a number of extra unneeded imports were added by Eclipse that cause the compile failures.  It is likely that Intellij + Eclipse would of done a better job of eliminating the unneeded imports if I had added all of the proper dependencies to the Intellij/Eclipse project.  Lesson learned :)

**Comment by scottmarlow** [comment]
There were too many bad webservices changes, so reverted those and squashed the rest.  Will build/test again now.

**Comment by scottmarlow** [comment]
https://ci.eclipse.org/jakartaee-tck/job/jakartaee-tck-scottmarlow/job/optimize_imports_eclipse/5/ passed the Full Platform tests.

**Comment by scottmarlow** [comment]
Next will be updating copyright date to 2020, I think that a glassfish-copyright-plugin change will be needed to deal with some Apache copyright statements.

**Comment by scottmarlow** [comment]
> Next will be updating copyright date to 2020, I think that a glassfish-copyright-plugin change will be needed to deal with some Apache copyright statements.

These changes were made.  

I created https://github.com/eclipse-ee4j/glassfish-copyright-plugin/issues/23 for better handling of the Apache v1.1 license references.

**Comment by scottmarlow** [comment]
> > https://ci.eclipse.org/jakartaee-tck/job/jakartaee-tck-scottmarlow/job/optimize_imports_eclipse/1/testReport/ had some test failures that need to be looked into.
> 
> I see the build has failures in this run. One of the causes is "import com.sun.jmx.mbeanserver.Repository.RegistrationContext" missing?

Addressed!

**Review by gurunrao — APPROVED** [review]
LGTM

**Review by RohitKumarJain — APPROVED** [review]
LGTM!!!

**Pull request merged**
