### PR TITLE
Update Jakarta Annotations documantation.

### PR DESCRIPTION
**Pull request by Tomas-Kraus**
Fixed version numbers to match current API version.

### CODE REVIEW

**Comment by Tomas-Kraus** [comment]
Modified user guide is here to review.
[Common-Annotations-TCK-Users-Guide.pdf](https://github.com/eclipse-ee4j/jakartaee-tck/files/4955078/Common-Annotations-TCK-Users-Guide.pdf)

**Comment by alwin-joseph** [comment]
Shouldn't below files need to be modified too?

user_guides/caj/src/main/jbake/content/title.adoc
user_guides/caj/src/main/jbake/templates/footer.ftl
user_guides/caj/src/main/jbake/assets/_config.yml

I updated these files too as in PR https://github.com/eclipse-ee4j/jakartaee-tck/pull/367

**Comment by Tomas-Kraus** [comment]
OK. Will do.

**Comment by Tomas-Kraus** [comment]
Updated PDF: [Common-Annotations-TCK-Users-Guide.pdf](https://github.com/eclipse-ee4j/jakartaee-tck/files/4955517/Common-Annotations-TCK-Users-Guide.pdf)

Listed files were modified too. Thanks for letting me know this Alwin.

**Comment by alwin-joseph** [comment]
> 
> p 7 (section 1.2.2) Have you tested on Windows 10 and Oracle Linux 7.1?

Tests were run  in CI  (centos7) & our local  (Oracle Linux 7). Is it expected to verify all TCKs in Windows 10.

**Comment by Tomas-Kraus** [comment]
> General point: The UG describes an independent CI, but It's not clear where this is published or released. The annotations project doesn't include a [download link](https://projects.eclipse.org/projects/ee4j.ca/downloads). The previous version CI for ballot used Eclipse GlassFish. The source can be obtained from the [2.0.0 tag](https://github.com/eclipse-ee4j/common-annotations-api/releases/tag/2.0.0). What is intended to be used? How would a user connect these dots to run this stand-alone TCK? Please consider expanding this section of the documentation.
> 
> Be sure to update the document status to FINAL before submitting with the final TCK.

I don't know answers here. I'm not commiter of Jakarta Annotations and I was never working on Annotations API, RI or TCK tests. It would be fine if someone with real development experience will review and update those things.

**Comment by Tomas-Kraus** [comment]
> p 7 (section 1.2.2) Have you tested on Windows 10 and Oracle Linux 7.1?

Changed to CentOS 7.

> p 9 (Section 1.2.6) Typo: how to get started with the CI CI. (this occurs in several places, perhaps it was intended to be Annotations CI (or CA CI). I recommend using Annotations when referring to the compatible implementation, or something that is not ambiguous.

Text is defined as `These instructions explain how to get started with the {TechnologyRI} CI.` and `TechnologyRI` was set to `CI`.
Changed `TechnologyRI` value to `Jakarta Annotations`.

> p 9 (section 1.3: similar (2nd bullet) One Example is CI (Jakarta Annotations, or CA)

This seems to be fixed too now.

> p 18 (section 3.2) 2nd bullet (similar to above)

This one too.

> p 19 (section 3.2, Follow these Steps:" 2.2) please verify the TCK Zip file name. I don't think they include the date in the file name)

I tested the build locally and it produced `annotations-tck-2.0.0_22-Jul-2020.zip` file name.
So I'm changing `TCKPackageName` to `annotations-tck-2.0.0_dd-Mmm-YYYY.zip`
I can't say that it's 100% correct. @alwin-joseph Can you confirm that it's OK?

> Be sure to update the document status to FINAL before submitting with the final TCK.

@m0mus Think I'll better leave it as DRAFT now.

**Comment by Tomas-Kraus** [comment]
Here are changes that I was able to fix myself.
[Common-Annotations-TCK-Users-Guide.pdf](https://github.com/eclipse-ee4j/jakartaee-tck/files/4960384/Common-Annotations-TCK-Users-Guide.pdf)

**Comment by Tomas-Kraus** [comment]
OK. According to note in pom:
```
        <!-- status: DRAFT, BETA, etc., or blank for final -->
        <status></status>
```
leaving status as blank.

**Comment by edbratt** [comment]
LGTM. Please review https://github.com/eclipse-ee4j/glassfish/pull/23136 for the TCK results details. With that, I think you can file the certification request against annotations-api/issues. Thank you!

**Pull request merged**
