### PR TITLE
jpa namespace update to jakartaee

### PR DESCRIPTION
**Pull request by alwin-joseph**

### CODE REVIEW

**Comment by scottmarlow** [comment]
@alwin-joseph do the pluggabliilty tests pass yet?

**Comment by alwin-joseph** [comment]
> @alwin-joseph do the pluggabliilty tests pass yet?

According to @lukasj  the jpa needs to implement the new namespaces after which we can apply this change to pass the tests . Current issue described in https://github.com/eclipse-ee4j/jakartaee-tck/issues/385

**Comment by gurunrao** [comment]
@alwin-joseph @scottmarlow @smillidge - IMO we should merge above namespace changes and create a tracking bug for new failures post that with JPA(if issue doesn't exist already).

**Comment by alwin-joseph** [comment]
> @alwin-joseph @scottmarlow @smillidge - IMO we should merge above namespace changes and create a tracking bug for new failures post that with JPA(if issue doesn't exist already).

+1

**Comment by scottmarlow** [comment]
:+1: from me as well, merging

**Comment by scottmarlow** [comment]
FYI, we built the Platform TCK with https://ci.eclipse.org/jakartaee-tck/job/eftl-jakartaeetck-build-900 and are now running the JPA tests via https://ci.eclipse.org/jakartaee-tck/job/eftl-jakartaeetck-run-900/29

**Comment by alwin-joseph** [comment]
> FYI, we built the Platform TCK with https://ci.eclipse.org/jakartaee-tck/job/eftl-jakartaeetck-build-900 and are now running the JPA tests via https://ci.eclipse.org/jakartaee-tck/job/eftl-jakartaeetck-run-900/29

killed the above as it was hung and started https://ci.eclipse.org/jakartaee-tck/job/eftl-jakartaeetck-run-900/30/

**Comment by scottmarlow** [comment]
https://www.eclipse.org/lists/jpa-dev/msg00073.html discusses the pending EclipseLink schema updates and dependent projects that need to be updated/released, which may not even be ready in the next few weeks.  I really would like to see all of the Jakarta EE 9 TCK tests passing by next week.

**Pull request merged**
