### PR TITLE
Update ts.jte settings when running with Java SE 17 to add --add-opens

### PR DESCRIPTION
**Pull request by scottmarlow**
**Fixes Issue**

(https://github.com/eclipse-ee4j/jakartaee-tck/issues/959) except for the `ejbembed` + `ejblitejsf` tests as per https://github.com/eclipse-ee4j/jakartaee-tck/issues/959#issuecomment-1121404341

**Describe the change**

Introduce JVMOPTS_RUNTESTCOMMAND system environment variable that can be referenced in ts.jte as needed to pass in additional JDK 17+ options as needed.

**Additional context**

(updated) https://github.com/eclipse-ee4j/jakartaee-tck/issues/962 may address test failures that we see with `ejblitejsf` (ViewHandlingStrategyNotFoundException).

For the `ejbembed` failures, it doesn't seem like the [JVMOPTS_RUNTESTCOMMAND change was used](tests as per https://github.com/eclipse-ee4j/jakartaee-tck/issues/959#issuecomment-1121404341).  From my local test output:
```
   [runcts] OUT => [javatest.batch] 05-09-2022 13:16:48:  Harness - keywords (to be passed to tests) set to:  all
   [runcts] OUT => [javatest.batch] 05-09-2022 13:16:48:  Harness - sClassPathFromExecProps = /tmp/ee10/jakartaeetck/bin/xml/../../dist/com/sun/ts/tests/ejb30/lite/singleton/dependson/triangle/ejbembed_vehicle_ejb.jar
   [runcts] OUT => [javatest.batch] command: com.sun.ts.lib.harness.ExecTSTestCmd CLASSPATH=/tmp/ee10/jakartaeetck/bin/xml/../../lib/tsharness.jar:/tmp/ee10/jakartaeetck/bin/xml/../../lib/cts.jar:/tmp/ee10/jakartaeetck/bin/xml/../../lib/glassfishporting.jar:/tmp/ee10/jakartaeetck/bin/xml/../../lib/commons-lang3-3.3.2.jar:/tmp/ee10/vi/glassfish7/glassfish/../javadb/lib/derbyclient.jar:/tmp/ee10/vi/glassfish7/glassfish/../javadb/lib/derbyshared.jar:/tmp/ee10/vi/glassfish7/glassfish/../javadb/lib/derbytools.jar:/tmp/ee10/vi/glassfish7/glassfish/lib/embedded/glassfish-embedded-static-shell.jar:/tmp/ee10/jakartaeetck/bin/xml/../../dist/com/sun/ts/tests/ejb30/lite/singleton/dependson/triangle/ejbembed_vehicle_ejb.jar DISPLAY=:0.0 HOME=/root TMP= windir= SYSTEMROOT= /home/smarlow/jdk-17/bin/java -Dcts.tmp=/tmp/ee10/jakartaeetck/bin/xml/../../tmp -Djava.util.logging.config.file=/tmp/ee10/vi/glassfish7/glassfish/domains/domain1/config/logging.properties -Dtest.ejb.stateful.timeout.wait.seconds=120 -Ddeliverable.class=com.sun.ts.lib.deliverable.cts.CTSDeliverable com.sun.ts.tests.common.vehicle.VehicleClient -p /tmp/ee10/jakartaeetck/bin/xml/../../tmp/tstest.jte -t triangleNoStartUp -vehicle ejbembed
   [runcts] OUT => [javatest.batch] ************************************************************
   [runcts] OUT => [javatest.batch] * props file set to "/tmp/root-cts-props.txt"
   [runcts] OUT => [javatest.batch] ************************************************************
   [runcts] OUT => [javatest.batch] [#|2022-05-09T13:16:48.525-0400|INFO||javax.enterprise.system.container.ejb.org.glassfish.ejb.embedded|_ThreadID=1;_ThreadName=main;_TimeMillis=1652116608525;_LevelValue=800;|[EJBContainerProviderImpl] Using installation location /tmp/ee10/vi/glassfish7/glassfish|#]
 ```

Perhaps the special `testExecuteEjbEmbed` handling in  https://github.com/eclipse-ee4j/jakartaee-tck/blob/master/src/com/sun/ts/lib/harness/TSScript.java#L382 is ignoring options that are not supported for the `testExecuteEjbEmbed` command.

CC @alwin-joseph @arjantijms

### CODE REVIEW

**Comment by alwin-joseph** [comment]
> #963 may address test failures that we see with `ejblitejsf` (ViewHandlingStrategyNotFoundException).

Small correction : https://github.com/eclipse-ee4j/jakartaee-tck/pull/962 is to address the test failures that we see with `ejblitejsf` in ejb30/lite/appexception suite.

**Comment by scottmarlow** [comment]
@dmatej https://gist.github.com/scottmarlow/5fb5d19538d732317edacc338b38d47b has the exception call stack for one of the embedded EJB test failures.   I was just reading your summary comment again on https://github.com/eclipse-ee4j/glassfish/issues/23915#issuecomment-1118223770 which I will quote part of here:
```
The current state is that if you want to use GF components directly (not using the server, but ie. ejb-container.jar), you have to set several add-opens JVM options. That applies also to embedded usages and clients used in the TCK.
```

Are you saying that we have to add the `several add-opens JVM options` on the (Platform TCK) JVM process that we are using the (embedded) ejb-container from?

I just wanted to confirm to make sure we go down the correct path with regard to adding the `add-opens` for the embedded case.

**Comment by scottmarlow** [comment]
Merging but I will create a new pull request based on further feedback here.

**Comment by arjantijms** [comment]
> Are you saying that we have to add the several add-opens JVM options on the (Platform TCK) JVM process that we are using the (embedded) ejb-container from?

I think that's the case indeed. See this one: https://github.com/eclipse-ee4j/glassfish/blob/master/appserver/tests/tck/embedded_ejb_smoke/runner/src/test/java/com/sun/ts/run/EmbeddedRunnerITest.java

The EJB embedded container directly runs the code that requires the add-opens.

**Pull request merged**
