### PR TITLE
Remove JAXR Coverage from TCK

### PR DESCRIPTION
**Pull request by gerdogdu**
Removing the JAXR related artifacts frmo TCK.

### CODE REVIEW

**Comment by gerdogdu** [comment]
Hi @gurunrao 
I did all of these removals. Can you please check and commit?
Regards.
Gurkan

**Comment by gerdogdu** [comment]
I did all changes but now getting conflicts because of others commit to master. I give up :(

**Comment by jgallimore** [comment]
@gerdogdu I'm just looking at this now. Are you open to me pushing a commit
to your PR (assuming I'm able)? I'd prefer to enable you to continue rather
than give up.

**Comment by gerdogdu** [comment]
@jgallimore Hi John, I have just pushed my final local changes. I think that conflict comes from jaxr package removals.

**Comment by gerdogdu** [comment]
@gurunrao I did all the jaxr changes and also tested it in my local environment to create TCK.zip bundle. It is working correctly.

**Comment by jgallimore** [comment]
👍 Don't give up... we're happy to help. Looks like there are still some conflicts. When I did the merged they were all files you had removed, so not to hard to resolved (just a lot of them!).

**Comment by gerdogdu** [comment]
@jgallimore thanks Jon. I learned the give-up when pushing your limits but nothing helps in some other projects :=

**Comment by scottmarlow** [comment]
Sorry about the xml conflicts, I have some more XSD changes left to make but will pause making them.

**Comment by gurunrao** [comment]
@gerdogdu - these downloaded fork you are working on. Followed these and was able to resolve conflict.Hope these helps.
============================================================
 git remote add upstream https://github.com/eclipse-ee4j/jakartaee-tck.git
 git fetch upstream
 git rebase upstream/master
 cd src/com/sun/ts/tests/
 rm -fr jaxr
 git add .
 git rebase --continue
=============================================================

**Comment by gerdogdu** [comment]
@gurunrao I did merge thank you. Now, the conflict has resolved.

**Comment by gerdogdu** [comment]
@gurunrao I did also build the TCK successfully.

**Comment by scottmarlow** [comment]
Thanks @gerdogdu for making this change!  Good to see that no other (non-JAXR) tests were removed.  Also thanks @RohitKumarJain @gurunrao @jgallimore for helping out!

**Pull request merged**
