### PR TITLE
implement empty removeServerAuthModule method.

### PR DESCRIPTION
**Pull request by gurunrao**
Fix platform TCK build failure with following message:
```
jaspic.lib.compile:
 [ts.javac] Compiling 40 source files to /home/jenkins/agent/workspace/jakartaee-tck_master/classes
 [ts.javac] Picked up JAVA_TOOL_OPTIONS: -Xmx6G
 [ts.javac] /home/jenkins/agent/workspace/jakartaee-tck_master/src/com/sun/ts/tests/jaspic/tssv/config/TSServerAuthConfig.java:203: warning: [deprecation] Boolean(boolean) in Boolean has been deprecated
 [ts.javac]       authMandatoryMap.put(layer + appContext, new Boolean(isMandatory));
 [ts.javac]                                                ^
 [ts.javac] /home/jenkins/agent/workspace/jakartaee-tck_master/src/com/sun/ts/tests/jaspic/tssv/config/TSAuthConfigFactory.java:54: error: TSAuthConfigFactory is not abstract and does not override abstract method removeServerAuthModule(Object) in AuthConfigFactory
 [ts.javac] public class TSAuthConfigFactory
 [ts.javac]        ^
 [ts.javac] /home/jenkins/agent/workspace/jakartaee-tck_master/src/com/sun/ts/tests/jaspic/tssv/config/TSAuthConfigFactoryForStandalone.java:56: error: TSAuthConfigFactoryForStandalone is not abstract and does not override abstract method removeServerAuthModule(Object) in AuthConfigFactory
 [ts.javac] public class TSAuthConfigFactoryForStandalone
 [ts.javac]        ^
 [ts.javac] Note: Some input files use unchecked or unsafe operations.
 [ts.javac] Note: Recompile with -Xlint:unchecked for details.
 [ts.javac] 2 errors
 [ts.javac] 1 warning

BUILD FAILED
/home/jenkins/agent/workspace/jakartaee-tck_master/bin/xml/ts.top.import.xml:391: The following error occurred while executing this line:
/home/jenkins/agent/workspace/jakartaee-tck_master/install/jakartaee/bin/build.xml:825: The following error occurred while executing this line:
/home/jenkins/agent/workspace/jakartaee-tck_master/install/jakartaee/bin/build.xml:838: The following error occurred while executing this line:
/home/jenkins/agent/workspace/jakartaee-tck_master/install/jakartaee/bin/build.xml:869: The following error occurred while executing this line:
/home/jenkins/agent/workspace/jakartaee-tck_master/install/jakartaee/bin/build.xml:799: Compile failed; see the compiler error output for details.
```

### CODE REVIEW

**Comment by scottmarlow** [comment]
CC @arjantijms

**Comment by scottmarlow** [comment]
@gurunrao are you already looking at the remaining failures?  From building locally with your branch, I see:
```
jakartaee-tck/src/com/sun/ts/tests/jaspic/spi/common/CommonTests.java:953: error: incompatible types: Properties cannot be converted to Map<String,String>
jakartaee-tck/src/com/sun/ts/tests/jaspic/spi/common/CommonTests.java:950: error: incompatible types: Properties cannot be converted to Map<String,String>
jakartaee-tck/src/com/sun/ts/tests/jaspic/spi/common/CommonTests.java:1045: error: incompatible types: Properties cannot be converted to Map<String,String>
jakartaee-tck/src/com/sun/ts/tests/jaspic/spi/common/CommonTests.java:1048: error: incompatible types: Properties cannot be converted to Map<String,String>
jakartaee-tck/src/com/sun/ts/tests/jaspic/spi/common/CommonTests.java:1103: error: incompatible types: Properties cannot be converted to Map<String,String>
jakartaee-tck/src/com/sun/ts/tests/jaspic/spi/common/CommonTests.java:1106: error: incompatible types: Properties cannot be converted to Map<String,String>
jakartaee-tck/src/com/sun/ts/tests/jaspic/spi/servlet/Client.java:3432: error: incompatible types: Properties cannot be converted to Map<String,String>
jakartaee-tck/src/com/sun/ts/tests/jaspic/spi/common/CommonUtils.java:106: error: incompatible types: Properties cannot be converted to Map<String,String>
```

**Comment by arjantijms** [comment]
As nothing is using that method atm, it can indeed be empty for now.

There's not super much time left, but we should of course add a test for this.

**Comment by gurunrao** [comment]
PR https://github.com/eclipse-ee4j/jakartaee-tck/pull/891 addresses same issue, hence closing the PR.

**Pull request closed without merging**
