### PR TITLE
Including permissions.xml at ear level.

### PR DESCRIPTION
**Pull request by RohitKumarJain**
Signed-off-by: RohitKumarJain <rohit.ku.jain@oracle.com>

### CODE REVIEW

**Comment by scottmarlow** [comment]
Will merge this in a few days, unless someone else can.

**Comment by alwin-joseph** [comment]
@scottmarlow  This change is done on master branch now. The CI jobs will build the bundles - jakartaee TCK & other standalone TCK bundles at https://download.eclipse.org/ee4j/jakartaee-tck/master/nightly/. 
Below are the jobs that will build the latest bundles : 
-https://ci.eclipse.org/jakartaee-tck/job/jakartaeetck-nightly-build-master/
-https://ci.eclipse.org/jakartaee-tck/job/standalonetck-nightly-build-run-master/

Please note the bundle versions are not updated here yet and need another change to append it.

**Comment by scottmarlow** [comment]
@alwin-joseph I assume that the reference to jakartaeetck-8.0.1.zip in [jakartaeetck-nightly-build-master/configure](https://ci.eclipse.org/jakartaee-tck/job/jakartaeetck-nightly-build-master/configure) needs to change to jakartaeetck-8.0.2.zip and a change like [jakartaee-tck/commit/6efae35b6594cb570ad5b575fee07eb0c4bee00d](https://github.com/eclipse-ee4j/jakartaee-tck/commit/6efae35b6594cb570ad5b575fee07eb0c4bee00d)?

**Comment by alwin-joseph** [comment]
> @alwin-joseph I assume that the reference to jakartaeetck-8.0.1.zip in [jakartaeetck-nightly-build-master/configure](https://ci.eclipse.org/jakartaee-tck/job/jakartaeetck-nightly-build-master/configure) needs to change to jakartaeetck-8.0.2.zip and a change like [jakartaee-tck/commit/6efae35b6594cb570ad5b575fee07eb0c4bee00d](https://github.com/eclipse-ee4j/jakartaee-tck/commit/6efae35b6594cb570ad5b575fee07eb0c4bee00d)?

Yes, exactly.

**Comment by scottmarlow** [comment]
@alwin-joseph I'll work on making that change.

**Comment by scottmarlow** [comment]
Note that the EE 8 challenge is now represented by [jakartaee-platform/issues#139](https://github.com/eclipse-ee4j/jakartaee-platform/issues/139)

**Pull request merged**
