### PR TITLE
eclipse-ee4j#212 - Remove Jakarta Management

### PR DESCRIPTION
**Pull request by RohitKumarJain**
Signed-off-by: RohitKumarJain <rohit.ku.jain@oracle.com>

### CODE REVIEW

**Comment by alwin-joseph** [comment]
I think you need changes in below files too. You can look for 'javaeemgmt' , 'j2eetools/mgmt' 'j2eetools-mgt'. Remove javax.management.j2ee-api.jar 
src/com/sun/ts/lib/harness/keyword.properties
bin/coverage-build.xml
docker/run_jakartaeetck.sh 
 install/jakartaee/bin/build.xml
install/jakartaee/bin/ts.jte 
install/jakartaee/other/vehicle.properties 

Thanks to Scott's PR https://github.com/eclipse-ee4j/jakartaee-tck/pull/292 , which can be referred for this.

**Comment by RohitKumarJain** [comment]
Thank you @alwin-joseph , I'll look into this.

**Comment by scottmarlow** [comment]
Should we also remove install/j2eemgmt/docs/J2EEMGMTJavaDocAssertions.html?

**Comment by RohitKumarJain** [comment]
> Should we also remove install/j2eemgmt/docs/J2EEMGMTJavaDocAssertions.html?

Thanks @scottmarlow , I have addressed your comment.

**Comment by RohitKumarJain** [comment]
Closing it because it is not allowing to resolve conflicts.

**Pull request closed without merging**
