### PR TITLE
Jsp plugin updates

### PR DESCRIPTION
**Pull request by markt-asf**
**Fixes Issue**
#937 

**Related Issue(s)**
Previous PR #938

**Describe the change**
Modify the TCK so jsp:plugin syntax in JSP pages is still validated but the action is a NO-OP in terms out HTML output.

**Additional context**
https://github.com/eclipse-ee4j/jsp-api/issues/226

CC @alwin-joseph @anajosep @arjantijms @cesarhernandezgt @dblevins @m0mus @edbratt @gurunrao @jansupol @jgallimore @kazumura @kwsutter @LanceAndersen @bhatpmk @RohitKumarJain @shighbar @gthoman @brideck @scottmarlow

### CODE REVIEW

**Review by arjantijms — APPROVED** [review]

**Review by scottmarlow — APPROVED** [review]

**Comment by alwin-joseph** [comment]
There are 5 test failures for Pages now , looks like related to this change.

https://ci.eclipse.org/jakartaee-tck/job/10/job/eftl-standalonetck-build-run-100/107/ 
GF: https://download.eclipse.org/ee4j/glassfish/glassfish-7.0.0-SNAPSHOT-nightly.zip 

@markt-asf Can you please suggest.

**Comment by markt-asf** [comment]
Glassfish's JSP engine will need updating to NO-OP `<jsp:plugin>` actions.

**Comment by arjantijms** [comment]
> Glassfish's JSP engine will need updating to NO-OP <jsp:plugin> actions.

Indeed. Easiest would be to make the updated TCK available at the usual location, and then I can easily do a PR for GF to pass that updated TCK.

**Comment by alwin-joseph** [comment]
> > Glassfish's JSP engine will need updating to NO-OP jsp:plugin actions.
> 
> Indeed. Easiest would be to make the updated TCK available at the usual location, and then I can easily do a PR for GF to pass that updated TCK.

The latest TCK is now available at https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee10/staged/eftl/jakarta-pages-tck-3.1.0.zip , built today (https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee10/staged/eftl/jakarta-pages-tck-3.1.0-tckinfo.txt).

**Pull request merged**
