### PR TITLE
JSTL migration from javax.servlet to jakarta.servlet

### PR DESCRIPTION
**Pull request by jbescos**
I tested it with apache-tomcat-10.0.0-M4 adding the next libs in the classpath of Tomcat:
derby.jar              derbyLocale_es.jar  derbyLocale_ja_JP.jar  derbyLocale_ru.jar     derbynet.jar            jakarta.servlet.jsp.jstl-2.0.0-SNAPSHOT.jar
derby.war              derbyLocale_fr.jar  derbyLocale_ko_KR.jar  derbyLocale_zh_CN.jar  derbyoptionaltools.jar  jakarta.servlet.jsp.jstl-api-2.0.0-RC1.jar
derbyLocale_cs.jar     derbyLocale_hu.jar  derbyLocale_pl.jar     derbyLocale_zh_TW.jar  derbyrun.jar
derbyLocale_de_DE.jar  derbyLocale_it.jar  derbyLocale_pt_BR.jar  derbyclient.jar        derbytools.jar

Test results: passed: 534; failed: 8

There are 4 type of failures. I imagine we need to test it with Glassfish because there are some differences if you compare it with Tomcat.
1 - Sigtest -> because I didn't generate the sigtest file.
2 - Related to redirection when not protocol is specified: <c:redirect url="/jstl/core/urlresource/param/import.jsp"/>. Tomcat sets the Location header without adding the protocol (http), and the TCK test fails because it pick that value from the header and it passes it to 'java.net.URL'. That fails with java.net.MalformedURLException: no protocol: /jstl_1_0_compat_web/jstl/core/urlresource/param/import.jsp
3 - Related to the charset encoding.
4 - One test fails because when there is an exception in JSP with a cause, the cause should be displayed, but it is doing it in the other way.

And one more thing I would like to notice:

There is already a generated war file in: jakartaee-tck/src/com/sun/ts/tests/jstl/compat/onedotzero/jstl_1_0_compat_web.war
This is not recreated, unless you explicitly create it in jakartaee-tck/src/com/sun/ts/tests/jstl/compat/onedotzero$ ant package.compat
I have regenerated it to pick all the changes I did in jsp files, otherwise tests fails because of some javax checks. I mention it because there is a  in that ant file.
I imagine the purpose is to validate compatibilty with JSTL 1, but it seems it is not the case anymore because of the new jakarta package.

I attach the test log and my jte in case somebody wants to take a look.
[jstl.zip](https://github.com/eclipse-ee4j/jakartaee-tck/files/4592021/jstl.zip)

### CODE REVIEW

**Comment by alwin-joseph** [comment]
@jbescos Thanks for this PR. I was trying to run the jstl tck this change on glassfish. There seems to be some issue with the jakartaee-tck/src/com/sun/ts/tests/jstl/compat/onedotzero/jstl_1_0_compat_web.war as it is not getting deployed.  Can you please help check why?

logs : https://ci.eclipse.org/jakartaee-tck/blue/rest/organizations/jenkins/pipelines/jakartaee-tck-alwin/branches/jstl-jakarta-servlet/runs/2/nodes/42/steps/53/log/?start=0

For our own reference, there are other wars also like  jstl_1_0_compat_web.war in commit https://github.com/eclipse-ee4j/jakartaee-tck/commit/308f725b8054afcdff67f68ec33395c784abea77. We might need to make similar change for those too.

**Comment by jbescos** [comment]
@alwin-joseph I cannot test it with glassfish 5.1.0 because doesn't implement jakarta.servlet. Many apps don't start because listeners don't implement jakarta.servlet interfaces.

But what I have seen is that there is jstltck-common.jar inside the war, with some missing common classes. In previous versions, that war file doesn't have any jar included, it is added later. I had to execute "package.compat" instead of "package".

I guess the issue is that ant "copy" has overwrite=false by default, so the correct jstltck-common.jar was not added, and the application was failing with ClassNotFoundException: com.sun.ts.tests.jstl.common.listeners.SQLContextListener. To know the reason we need to check the Glassfish log.

I have done a commit with empty lib in the war, could you try again?. If it fails, could you give me a link with the Glassfish you are trying so I can reproduce it by my self?.

If I compare my log with yours, I have one step that you don't have. Here I can see that the war is unzipped and enriched with libs.
```
package:
    [mkdir] Created dir: /home/jbescos/workspace/jakartaee-tck/webtmp
    [mkdir] Created dir: /home/jbescos/workspace/jakartaee-tck/dist/com/sun/ts/tests/jstl/compat/onedotzero
    [unjar] Expanding: /home/jbescos/workspace/jakartaee-tck/src/com/sun/ts/tests/jstl/compat/onedotzero/jstl_1_0_compat_web.war into /home/jbescos/workspace/jakartaee-tck/webtmp
   [delete] Deleting directory /home/jbescos/workspace/jakartaee-tck/webtmp/META-INF
     [copy] Copying 3 files to /home/jbescos/workspace/jakartaee-tck/webtmp/WEB-INF/lib
      [jar] Building jar: /home/jbescos/workspace/jakartaee-tck/dist/com/sun/ts/tests/jstl/compat/onedotzero/jstl_1_0_compat_web.war
   [delete] Deleting directory /home/jbescos/workspace/jakartaee-tck/webtmp
```

**Comment by alwin-joseph** [comment]
> @alwin-joseph I cannot test it with glassfish 5.1.0 because doesn't implement jakarta.servlet. Many apps don't start because listeners don't implement jakarta.servlet interfaces.
> 
> But what I have seen is that there is jstltck-common.jar inside the war, with some missing common classes. In previous versions, that war file doesn't have any jar included, it is added later. I had to execute "package.compat" instead of "package".
> 
> I guess the issue is that ant "copy" has overwrite=false by default, so the correct jstltck-common.jar was not added, and the application was failing with ClassNotFoundException: com.sun.ts.tests.jstl.common.listeners.SQLContextListener. To know the reason we need to check the Glassfish log.
> 
> I have done a commit with empty lib in the war, could you try again?. If it fails, could you give me a link with the Glassfish you are trying so I can reproduce it by my self?.
> 
> If I compare my log with yours, I have one step that you don't have. Here I can see that the war is unzipped and enriched with libs.
> 
> ```
> package:
>     [mkdir] Created dir: /home/jbescos/workspace/jakartaee-tck/webtmp
>     [mkdir] Created dir: /home/jbescos/workspace/jakartaee-tck/dist/com/sun/ts/tests/jstl/compat/onedotzero
>     [unjar] Expanding: /home/jbescos/workspace/jakartaee-tck/src/com/sun/ts/tests/jstl/compat/onedotzero/jstl_1_0_compat_web.war into /home/jbescos/workspace/jakartaee-tck/webtmp
>    [delete] Deleting directory /home/jbescos/workspace/jakartaee-tck/webtmp/META-INF
>      [copy] Copying 3 files to /home/jbescos/workspace/jakartaee-tck/webtmp/WEB-INF/lib
>       [jar] Building jar: /home/jbescos/workspace/jakartaee-tck/dist/com/sun/ts/tests/jstl/compat/onedotzero/jstl_1_0_compat_web.war
>    [delete] Deleting directory /home/jbescos/workspace/jakartaee-tck/webtmp
> ```

I pulled your changes to https://github.com/alwin-joseph/jakartaee-tck/tree/jstl-jakarta-servlet. The CI job https://ci.eclipse.org/jakartaee-tck/job/testjstl/ can be run that picks changes from this repo. If you want to test you can commit to this repo and trigger this job. Latest logs https://ci.eclipse.org/jakartaee-tck/blue/rest/organizations/jenkins/pipelines/jakartaee-tck-alwin/branches/jstl-jakarta-servlet/runs/3/nodes/48/steps/53/log/?start=0 does have the step you mentioned.

I think the additional step that we have is the ant deploy.all before the test run.

**Comment by jbescos** [comment]
The reason of the failure is that glassfish5 doesn't have the jakarta.servlet libraries. This is why I had to test it in apache-tomcat-10.0.0-M4. 

So one the application tries to deploy in Glassfish there is a:
java.lang.Exception: java.lang.IllegalStateException: ContainerBase.addChild: start: org.apache.catalina.LifecycleException: java.lang.IllegalArgumentException: java.lang.NoClassDefFoundError: jakarta/servlet/ServletContextListener

I forgot to say it in my initial commit. This tests cannot run till Glassfish is updated with

**Comment by alwin-joseph** [comment]
> The reason of the failure is that glassfish5 doesn't have the jakarta.servlet packages. This is why I had to test it in apache-tomcat-10.0.0-M4.
> 
> When the application tries to deploy in Glassfish there is a: java.lang.NoClassDefFoundError: jakarta/servlet/ServletContextListener
> 
> I forgot to say it in my initial comment. This tests cannot run in Glassfish till it is updated with jakarta.servlet packages.

Thanks @jbescos 

Can you provide the ant commands used for setup and running the test in tomcat. Isn't ant deploy.all required ? I wanted to check if https://github.com/eclipse-ee4j/jakartaee-tck/blob/master/docker/jstltck.sh require changes.

**Comment by jbescos** [comment]
Yes, but keep in mid that Tomcat has a very small classpath and you will need to add all the dependencies that TCK tests needs. In the case of JSTL it is very simple, but for example for JAXRS it is very difficult (because it needs Jersey, HK2, and a big etc).

Download the Tomcat 10 here:
https://tomcat.apache.org/download-10.cgi

[scripts.zip](https://github.com/eclipse-ee4j/jakartaee-tck/files/4608882/scripts.zip)

Put previous files somewhere in your computer. In my case I have them in /home/jbescos/workspace/scripts

Check in the scripts the variables, so it is according to your file system:
export TS_HOME=~/workspace/jakartaee-tck
export ANT_HOME=~/programs/apache-ant-1.9.14
export JAVA_HOME=~/programs/java/jdk1.8.0_231
TOMCAT=~/programs/apache-tomcat-10.0.0-M4

The way I executed this is:
/home/jbescos/workspace/scripts/jakartaee-tck.sh jstl

And also expect to make some changes in Tomcat to make it more similar to Glassfish. For example default character encoding in Tomcat is utf-8, the http connector doesn't accept TRACE, etc. It is difficult to have it fully working.

**Comment by alwin-joseph** [comment]
> For tomcat I don't use deploy.all. I copy paste the war files in the webapp folder (this is done in the attached script tomcatRedeploy.sh).
> 
> Keep in mind that Tomcat has a very small classpath and you will need to add all the dependencies that TCK tests needs. In the case of JSTL it is very simple, but for example for JAXRS it is very difficult (because it needs Jersey, HK2, and a big etc).
> 
> Download the Tomcat 10 here:
> https://tomcat.apache.org/download-10.cgi
> 
> [scripts.zip](https://github.com/eclipse-ee4j/jakartaee-tck/files/4608882/scripts.zip)
> 
> Put previous files somewhere in your computer. In my case I have them in /home/jbescos/workspace/scripts
> 
> Check in the scripts the variables, so it is according to your file system:

Thanks. I was more interested to know if ant deploy.all is run or not for tomcat. Currently the tests fail for glassfish as expected but the ant deploy.all fails with below : 

  [gf.echo] Deploying archive:  /home/jenkins/agent/workspace/e-tck-alwin_jstl-jakarta-servlet/tags-tck/dist/com/sun/ts/tests/jstl/compat/onedotzero/jstl_1_0_compat_web.war
  [gf.echo] Deployment Failed:  jstl_1_0_compat_web.war
BUILD FAILED
/home/jenkins/agent/workspace/e-tck-alwin_jstl-jakarta-servlet/tags-tck/bin/xml/ts.top.import.xml:288: The following error occurred while executing this line:
/home/jenkins/agent/workspace/e-tck-alwin_jstl-jakarta-servlet/tags-tck/bin/xml/impl/glassfish/deploy.xml:68: The following error occurred while executing this line:
/home/jenkins/agent/workspace/e-tck-alwin_jstl-jakarta-servlet/tags-tck/bin/xml/impl/glassfish/deploy.xml:142: The following error occurred while executing this line:
/home/jenkins/agent/workspace/e-tck-alwin_jstl-jakarta-servlet/tags-tck/bin/xml/impl/glassfish/deploy.xml:202: Deployment Failed for one or more archives.  Check the server log to see which failed.

Hence I wanted to check if there is any issue with the jstl_1_0_compat_web.war file generated.
I think we can revisit the issue later once we start running tests with glassfish.

**Comment by alwin-joseph** [comment]
With this merge a bunch of compile issues are expected to be resolved for jakartaee-tck build.

**Pull request merged**
