### PR TITLE
Add new glassfishporting jar with SunRILoginContext

### PR DESCRIPTION
**Pull request by alwin-joseph**
**Fixes Issue**
https://github.com/eclipse-ee4j/jakartaee-tck/issues/583 

**Describe the change**
As suggested in https://github.com/eclipse-ee4j/jakartaee-tck/issues/583#issuecomment-776115616 the com.sun.ts.lib.implementation.sun.javaee.SunRILoginContext is moved out of cts.jar and added to a new glassfishporting.jar at lib/. 

If there are other better solutions that can be considered as longer goals.
 

**Additional context**
Below commands were used to generate the glassfishporting.jar using glassfish6 & jakartaeetck(9.0.0):
 - javac -cp ../glassfish6/glassfish/modules/security.jar:../lib/cts.jar:../lib/tsharness.jar com/sun/ts/lib/implementation/sun/javaee/SunRILoginContext.java 
- jar cf glassfishporting.jar com/sun/ts/lib/implementation/sun/javaee/SunRILoginContext.class

### CODE REVIEW

**Comment by arjantijms** [comment]
Does it make sense to rename it right away to GlassFishLoginContext? I know the terms "sun", "ri", "pe", "ias", "v3" etc etc are still all over the place, but every little one that gets fixed is one ;)

**Review by scottmarlow — APPROVED** [review]

**Comment by scottmarlow** [comment]
> Does it make sense to rename it right away to GlassFishLoginContext? I know the terms "sun", "ri", "pe", "ias", "v3" etc etc are still all over the place, but every little one that gets fixed is one ;)

I'm not against that change but the ts.jte config + doc would need to reference the new class name.

**Review by gurunrao — COMMENTED** [review]
copyright year update to 2021 is missing in ts.jte file.

**Comment by alwin-joseph** [comment]
> Does it make sense to rename it right away to GlassFishLoginContext? I know the terms "sun", "ri", "pe", "ias", "v3" etc etc are still all over the place, but every little one that gets fixed is one ;)

Done.

**Comment by alwin-joseph** [comment]
> > Does it make sense to rename it right away to GlassFishLoginContext? I know the terms "sun", "ri", "pe", "ias", "v3" etc etc are still all over the place, but every little one that gets fixed is one ;)
> 
> I'm not against that change but the ts.jte config + doc would need to reference the new class name.

I replaced SunRILoginContext to GlassFishLoginContext. I did not find the occurence of SunRILoginContext in docs yet, if any change required will address them in later changes.

**Comment by scottmarlow** [comment]
> > > Does it make sense to rename it right away to GlassFishLoginContext? I know the terms "sun", "ri", "pe", "ias", "v3" etc etc are still all over the place, but every little one that gets fixed is one ;)
> > 
> > 
> > I'm not against that change but the ts.jte config + doc would need to reference the new class name.
> 
> I replaced SunRILoginContext to GlassFishLoginContext. I did not find the occurence of SunRILoginContext in docs yet, if any change required will address them in later changes.

Thanks, I see that the ts.jte files were updated so looks good!

**Pull request merged**
