### PR TITLE
Renaming javax_xml_soap ==> jakarta_xml_soap with folder and its references…

### PR DESCRIPTION
**Pull request by RohitKumarJain**
Signed-off-by: RohitKumarJain <rohit.ku.jain@oracle.com>

### CODE REVIEW

**Comment by alwin-joseph** [comment]
Thanks for the PR. Can you also correct the copyright year in the modified files.

**Comment by RohitKumarJain** [comment]
@alwin-joseph , sure I'll take care of copyright year in the modified files.

**Comment by RohitKumarJain** [comment]
fixed as part of commit:  https://github.com/RohitKumarJain/jakartaee-tck/commit/1850af2a6e4707e948755c119a8226731e6ae2ba

**Comment by scottmarlow** [comment]
Thanks for reviewing @alwin-joseph + @gurunrao !  

Thanks for the change @RohitKumarJain !  

Very much appreciated all!

**Pull request merged**
