### PR TITLE
Remove Concurrency TCK

### PR DESCRIPTION
**Pull request by KyleAure**
**Fixes Issue**
Partially addresses #757

**Related Issue(s)**
Similar to #809

**Describe the change**
The Concurrency TCK is now being developed and deployed externally as part of the Concurrency API repo: https://github.com/eclipse-ee4j/concurrency-api/tree/master/tck

**Additional context**
I can squash the commits down to a single commit after review. Keeping them separate will allow for easier review. 

CC @alwin-joseph @anajosep @arjantijms @cesarhernandezgt @dblevins @m0mus @edbratt @gurunrao @jansupol @jgallimore @kazumura @kwsutter @LanceAndersen @bhatpmk @RohitKumarJain @shighbar @gthoman @brideck @scottmarlow

### CODE REVIEW

**Comment by gurunrao** [comment]
For Platform TCK runs of concurrency testsuite api tests, new concurrency TCK will have to support `ejb servlet jsp` vehicles(https://github.com/eclipse-ee4j/jakartaee-tck/blob/master/install/jakartaee/other/vehicle.properties#L55), unless ejb, servlet, jsp vehicles are supported by migrated/split concurrency TCK, sources at https://github.com/eclipse-ee4j/jakartaee-tck/tree/master/src/com/sun/ts/tests/concurrency/api cannot be removed.

**Comment by KyleAure** [comment]
@gurunrao Thanks for the heads up.  I have a plan for implementing a similar framework to the vehicles used in the TCK in this repo.  I don't think it's feasible to get it in for Jakarta 10, it might have to wait until Jakarta 11.

**Comment by scottmarlow** [comment]
@gurunrao @KyleAure FYI, https://docs.google.com/document/d/1V1dDLJkd14EDRMPeuI0VzPtU4Lbli8FFBd1pLDLlOrY/edit#bookmark=id.3605pdv1yuo8 has some costs for Standalone SPEC TCKs to validate Platform requirements like EJB (if the Enterprise Beans SPEC changes after the Concurrency SPEC is final, the Concurrency SPEC may need to release again with further TCK changes to deal with updating the EJB TCK tests).

If you do add `ejb servlet jsp` tests to the Concurrency TCK, there should be a way to choose between running the `Java SE` versus `Jakarta EE` tests.  

In case it helps, the CDI TCK has options for choosing between `SE[`](https://eclipse-ee4j.github.io/cdi-tck/#_running_the_tests_in_the_container_se_part) and `[EE](https://eclipse-ee4j.github.io/cdi-tck/#_running_the_tests_in_the_container_core_and_ee_parts)`.

**Comment by scottmarlow** [comment]
@KyleAure could you please send email to the Platform, Platform TCK, Concurrency mailing lists asking for a review of this pull request for removal of duplicate Concurrency tests from the Platform TCK? Or ping me back if you would prefer that I send that, either way is fine.

https://github.com/eclipse-ee4j/jakartaee-platform/wiki/Guidelines_For_Standalone_TCKs mentions that we want the different teams to have a chance to review changes that remove Platform TCK tests due to duplication between Standalone TCK + Platform TCK.

**Comment by KyleAure** [comment]
@scottmarlow  Thank you for the feedback, Scott.  I went ahead and opened issues in the Concurrency TCK for the gaps you mentioned previously, and send out an email to the lists you mentioned asking for more feedback.

**Comment by gurunrao** [comment]
signature tests will be retained for Platform TCK tests.

**Comment by gurunrao** [comment]
@KyleAure - please resolve conflicts.

**Comment by KyleAure** [comment]
@gurunrao Merge conflicts resolved

**Comment by KyleAure** [comment]
@scottmarlow Yes, porting the docs is next on my list thanks for pointing that out.

**Comment by gurunrao** [comment]
https://github.com/jakartaee/concurrency/issues/196 is closed, are there any other dependencies for the PR?

**Review by gurunrao — APPROVED** [review]

**Pull request merged**
