### PR TITLE
JPA Tests for JPQL EXTRACT support added in JPA 3.1

### PR DESCRIPTION
**Pull request by Tomas-Kraus**
name: Pull Request
about: Create a pull request for a Platform TCK change
title: 'JPA Tests for JPQL EXTRACT support added in JPA 3.1'
labels: ''
assignees: ''

---

**Fixes Issue**
TCK Tests for https://github.com/eclipse-ee4j/jpa-api/pull/314

**Related Issue(s)**
https://github.com/eclipse-ee4j/jpa-api/issues/102

**Describe the change**
Tests for new JPQL EXTRACT grammar changes.

**Additional context**
N/A

CC @alwin-joseph @anajosep @arjantijms @cesarhernandezgt @dblevins @m0mus @edbratt @gurunrao @jansupol @jgallimore @kazumura @kwsutter @LanceAndersen @bhatpmk @RohitKumarJain @shighbar @gthoman @brideck @scottmarlow

### CODE REVIEW

**Comment by Tomas-Kraus** [comment]
Let's keep this as draft until PR https://github.com/eclipse-ee4j/jpa-api/pull/314 is merged and new spec assertion IDs are generated.

**Comment by gurunrao** [comment]
@Tomas-Kraus - https://ci.eclipse.org/jakartaee-tck/job/jakartaee-tck/job/master/1672/artifact/jpatck.log has two failure for following tests

- com/sun/ts/tests/jpa/core/annotations/access/field/Client.java#testExtractDateTimeQuarter
- com/sun/ts/tests/jpa/core/annotations/access/field/Client.java#testExtractDateQuarter

**Comment by gurunrao** [comment]
@Tomas-Kraus  - Please refer attached logs - [jpatck.log](https://github.com/eclipse-ee4j/jakartaee-tck/files/8203644/jpatck.log) for details on ^ test failures.

**Comment by Tomas-Kraus** [comment]
This was already fixed in EclipseLink.

**Pull request merged**
