### PR TITLE
Modified TCKs for jakarta.annotation.ManagedBean

### PR DESCRIPTION
**Pull request by kwsutter**
Signed-off-by: Kevin Sutter <kwsutter@gmail.com>

No idea if you want these type of changes piece meal or not...  But, I am working on the Managed Beans 2.0 update for Jakarta EE 9.  Since the TCK for ManagedBeans is covered by the Platform TCK, I tried to find where the Platform TCK is affected.  Not sure if making this change without having the rest of the java->jakarta changes available is useful or not.  But, since the [Annotations API RC](https://repo1.maven.org/maven2/jakarta/annotation/jakarta.annotation-api/2.0.0-RC1/) is available, then these ManagedBean changes could be built with this RC.

I thought I would go ahead and create this PR and have the discussion.

### CODE REVIEW

**Comment by jansupol** [comment]
Please do not modify sig files. Those are for versions 1.2 and 1.3. The new version should have a new signature file.
As far as I understand it Jakarta EE 9 will support JDK 8 and JDK11. So a new file for JDK9 is not needed.
Recording the signature files for JDK 11 is not that simple. I do not think the file is needed in this very commit, the signature files can be added later, in a separate commit.

**Comment by kwsutter** [comment]
Thanks, @jansupol, for the education on the signature tests.  I have removed all of the files relating to signature testing since it sounds like that mechanism is still under discussion and will probably be done all at once.  But, I did go ahead and create this new file since it will probably be needed...  src/com/sun/ts/tests/signaturetest/signature-repository/jakarta.annotation.sig_2.0_se8

**Comment by kwsutter** [comment]
Just for reference, there is a good discussion on the TCK mailing list talking about how to move forward with the Jakarta EE 9 TCK updates:  https://www.eclipse.org/lists/jakartaee-tck-dev/msg00291.html

**Comment by alwin-joseph** [comment]
Hi @kwsutter : Thanks for this change. 
Could you please remove the  src/com/sun/ts/tests/signaturetest/signature-repository/jakarta.annotation.sig_2.0_se8 file from this PR. I suspect this above sig file might be generated using older sigtest jars currently in the repo . 
I will make the signature file changes in https://github.com/eclipse-ee4j/jakartaee-tck/pull/169.

**Comment by scottmarlow** [comment]
@kwsutter sorry for the late review, nice to see the copyright date update.  

Some files have lines with just whitespace changes.  I hit the same issue, as I had my editor (Intellij) configured to truncate trailing whitespace by default.  

I will update [https://github.com/eclipse-ee4j/jakartaee-tck/pull/161] to not also change javax.annotation classes.  My mistake, oops. :)

**Comment by kwsutter** [comment]
> Hi @kwsutter : Thanks for this change.
> Could you please remove the src/com/sun/ts/tests/signaturetest/signature-repository/jakarta.annotation.sig_2.0_se8 file from this PR. I suspect this above sig file might be generated using older sigtest jars currently in the repo .
> I will make the signature file changes in #169.

Done.  Thanks!

**Comment by kwsutter** [comment]
> @kwsutter sorry for the late review, nice to see the copyright date update.
> 
> Some files have lines with just whitespace changes. I hit the same issue, as I had my editor (Intellij) configured to truncate trailing whitespace by default.
> 
Thanks for the idea.  I just use the simple Atom editor and it was also configured to truncate trailing whitespace by default.  I have now changed it.  Thanks for the idea!

> I will update [https://github.com/[/pull/161](https://github.com/eclipse-ee4j/jakartaee-tck/pull/161)] to not also change javax.annotation classes. My mistake, oops. :)

Just so we get them covered...  Thanks!

**Comment by kwsutter** [comment]
@alwin-joseph and @scottmarlow Thanks for the reviews!  I think your comments are resolved.  Is there anything else preventing this from moving forward?  Thanks.

**Comment by scottmarlow** [comment]
Looks good to me!  Thanks Kevin!

**Pull request merged**
