### PR TITLE
Build fix for jaxws namespaces

### PR DESCRIPTION
**Pull request by senivam**
Signed-off-by: Maxim Nesen <maxim.nesen@oracle.com>

### CODE REVIEW

**Comment by alwin-joseph** [comment]
@senivam Thanks for this change. Could you invoke this script from below lines to pass the jaxws & platform tck builds.

https://github.com/eclipse-ee4j/jakartaee-tck/blob/3b3cd1c6d7b0d7ea33f0a6d9b62980aab228c96a/docker/build_standalone-tcks.sh#L189

https://github.com/eclipse-ee4j/jakartaee-tck/blob/3b3cd1c6d7b0d7ea33f0a6d9b62980aab228c96a/docker/build_jakartaeetck.sh#L106

**Comment by senivam** [comment]
@alwin-joseph I've applied the fix as requested. I've rebased changes to 1 commit for further better rolling back (that is why force push shall be applied).

**Comment by alwin-joseph** [comment]
Looks like there are issues while building   :

 [wsimport] [WARNING] s4s-elt-schema-ns: The namespace of element 'bindings' must be from the schema namespace, 'http://www.w3.org/2001/XMLSchema'.
 [wsimport]   line 5 of http://dummy.pseudo-schema#schema2
 [wsimport] 
 [wsimport] [WARNING] s4s-elt-invalid: Element 'bindings' is not a valid element in a schema document.
 [wsimport]   line 5 of http://dummy.pseudo-schema#schema2
 [wsimport] 
 [wsimport] [WARNING] schema_reference.4: Failed to read schema document 'http://dummy.pseudo-schema#schema2', because 1) could not find the document; 2) the document could not be read; 3) the root element of the document is not <xsd:schema>.
 [wsimport]   line 5 of http://dummy.pseudo-schema#schema2
 [wsimport] 
 [wsimport] [WARNING] No JAXB customization was detected in the schema but the prefix "jaxb" is used for other namespace URIs. If you did intend to use JAXB customization, make sure the namespace URI is "http://java.sun.com/xml/ns/jaxb"
 [wsimport]   line 80 of file:/home/jenkins/agent/workspace/jakartaee-tck-alw_pr_510/src/com/sun/ts/tests/jaxws/sharedwebservices/doclithelloservice/WSDLHelloService.wsdl
 [wsimport] 
 [wsimport] [ERROR] Unexpected <bindings> appears at line 5 column 17
 [wsimport]   line 5 of http://dummy.pseudo-schema#schema2

jaxws tck build job url : https://ci.eclipse.org/jakartaee-tck/job/jakartaee-tck-alw/job/pr%252F510/2/
jaxws tck build log :  https://ci.eclipse.org/jakartaee-tck/blue/rest/organizations/jenkins/pipelines/jakartaee-tck-alw/branches/pr%252F510/runs/2/nodes/29/steps/32/log/?start=0

Were you able to successfully build jaxws tck using these changes.

**Comment by senivam** [comment]
@alwin-joseph could you please update your Git and re-run? I've fixed the error - it was zip instead of jar extension for jaxb-osgi. Thank you.

**Comment by alwin-joseph** [comment]
Thanks the latest changes fixed the jaxws tck build - https://ci.eclipse.org/jakartaee-tck/job/jakartaee-tck-alw/job/pr%252F510/5/

I also see platform tck build issues now reduced to below now.

[dosubdirs] BUILD FAILED
[dosubdirs] The following directories failed:
[dosubdirs] /home/jenkins/agent/workspace/jakartaee-tck-alw_pr_510/bin/xml/../../src/com/sun/ts/tests/servlet/ee/common/sharedwebservices/servlethttptestservice
[dosubdirs] /home/jenkins/agent/workspace/jakartaee-tck-alw_pr_510/bin/xml/../../src/com/sun/ts/tests/webservices12/ejb/annotations/HandlerTest/client
[dosubdirs] /home/jenkins/agent/workspace/jakartaee-tck-alw_pr_510/bin/xml/../../src/com/sun/ts/tests/webservices12/ejb/annotations/HandlerTest/server
[dosubdirs] /home/jenkins/agent/workspace/jakartaee-tck-alw_pr_510/bin/xml/../../src/com/sun/ts/tests/webservices12/ejb/annotations/WSEjbSOAPHandlersTest
[dosubdirs] /home/jenkins/agent/workspace/jakartaee-tck-alw_pr_510/bin/xml/../../src/com/sun/ts/tests/webservices12/ejb/annotations/WSEjbSOAPHandlersTest2
[dosubdirs] /home/jenkins/agent/workspace/jakartaee-tck-alw_pr_510/bin/xml/../../src/com/sun/ts/tests/webservices12/ejb/descriptors/WSEjbOverrideWSRefHCWithDDsTest
[dosubdirs] /home/jenkins/agent/workspace/jakartaee-tck-alw_pr_510/bin/xml/../../src/com/sun/ts/tests/webservices12/servlet/HandlerTest/client
[dosubdirs] /home/jenkins/agent/workspace/jakartaee-tck-alw_pr_510/bin/xml/../../src/com/sun/ts/tests/webservices12/servlet/HandlerTest/server

job url : https://ci.eclipse.org/jakartaee-tck/blue/organizations/jenkins/jakartaee-tck-alw/detail/pr%2F510/6/pipeline/21
logs : https://ci.eclipse.org/jakartaee-tck/blue/rest/organizations/jenkins/pipelines/jakartaee-tck-alw/branches/pr%252F510/runs/6/nodes/21/steps/24/log/?start=0 

Any idea if it requires version attribute or more missing schema changes here.

**Review by alwin-joseph — APPROVED** [review]

**Comment by alwin-joseph** [comment]
To repeat , this change will be reverted once the integration to glassfish is done

**Comment by senivam** [comment]
Hi @alwin-joseph , I will do another PR to fix those failures, but that another PR shall not be reverted because those will be forgotten namespace changes.

**Comment by senivam** [comment]
@alwin-joseph PR is submitted as #512

**Pull request merged**
