### PR TITLE
Update Platform TCK version from 10 to 11

### PR DESCRIPTION
**Pull request by scottmarlow**
Signed-off-by: Scott Marlow <smarlow@redhat.com>

Update Platform TCK version in documentation and various build files.

CC @alwin-joseph @anajosep @arjantijms @cesarhernandezgt @dblevins @m0mus @edbratt @gurunrao @jansupol @jgallimore @kazumura @kwsutter @LanceAndersen @bhatpmk @RohitKumarJain @shighbar @gthoman @brideck @scottmarlow

### CODE REVIEW

**Comment by gurunrao** [comment]
@scottmarlow IMO, we need to tag 10.0.0 Final before merge of the PR(we do have Tag until RC3).

**Comment by scottmarlow** [comment]
RC3 does represent what final was based on, I pushed a new tag https://github.com/eclipse-ee4j/jakartaee-tck/releases/tag/10.0.0.Final which is more clear.

**Comment by gurunrao** [comment]
> @gurunrao RC3 does represent what EE 10 Platform TCK final was based on, I pushed a new tag https://github.com/eclipse-ee4j/jakartaee-tck/releases/tag/10.0.0.Final which is more clear (https://github.com/eclipse-ee4j/jakartaee-tck/tree/10.0.x is the branch for maintaining EE 10 Platform TCK).

post merge of PR https://github.com/eclipse-ee4j/jakartaee-tck/pull/1112, Final TCK was built on 2022-08-16, we can refer https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee10/staged/eftl/jakarta-jakartaeetckinfo.txttck info txt for the exact timestamp. RC3 was marked on 9-Aug, which is a different date. final commits are with https://github.com/eclipse-ee4j/jakartaee-tck/pull/1112 for Jakarta EE 10 Platform TCK and should be tagged as Final.

**Comment by scottmarlow** [comment]
For reference https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee10/staged/eftl/jakarta-jakartaeetckinfo.txt has:
```
***********************************************************************************
***                        TCK bundle information                               ***
*** Name:       jakarta-jakartaeetck-10.0.0.zip                                     ***
*** Bundle Copied to URL:    https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee10/staged/eftl//jakarta-jakartaeetck-10.0.0.zip ***
*** Date and size: date: 2022-08-16 16:06:43.000000000 +0000, size(b): 527767518        ***
*** SHA256SUM: 7874244f69ed9c72f4d4b5a8c48b21d39c56f4b877b1d4d735247a7f08215a5e ***
***                                                                             ***
***********************************************************************************
```

**Comment by scottmarlow** [comment]
> > @gurunrao RC3 does represent what EE 10 Platform TCK final was based on, I pushed a new tag https://github.com/eclipse-ee4j/jakartaee-tck/releases/tag/10.0.0.Final which is more clear (https://github.com/eclipse-ee4j/jakartaee-tck/tree/10.0.x is the branch for maintaining EE 10 Platform TCK).
> 
> post merge of PR #1112, Final TCK was built on 2022-08-16, we can refer https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee10/staged/eftl/jakarta-jakartaeetckinfo.txttck info txt for the exact timestamp. RC3 was marked on 9-Aug, which is a different date. final commits are with #1112 for Jakarta EE 10 Platform TCK and should be tagged as Final.

Good catch, agreed we should include the additional commits used in final build of Platform TCK on 2022-08-16.

**Comment by dmatej** [comment]
If it would be possible, I would use current master as the final 10.0.0, because before that the bash script is bit unstable. It doesn't matter in virtual containers used by Jenkins, so after the build they go to "virtual heaven", but when you try to run the TCK on own computer, it leaves garbage after each run.
With the current master we can run any TCK tests anywhere, see https://github.com/eclipse-ee4j/glassfish/tree/master/appserver/tests/tck and especially https://github.com/eclipse-ee4j/glassfish/tree/master/appserver/tests/tck/tck-runner.
Currently I use locally built master branch of the jakartaee-tck to run that, uploaded to private Nexus.

**Comment by scottmarlow** [comment]
@dmatej currently we need Jakarta EE Specification committee permission to include TCK changes in service releases beyond just excluding challenged tests.  The changes that were merged after we built the Platform TCK on August 16, 2022 cannot just be included in the next 10.0.1 Platform TCK that we build for a TCK challenge (at least not without getting permission from Spec committee concurrently).  

Are the changes that you want specific to running GlassFish TCK testing?  Perhaps those could be in a branch for the GlassFish TCK Porting kit so you have a place to make further improvements.

**Comment by dmatej** [comment]
Ok, thanks for explanation!
Currently we use Jenkins results for the certification, but in the future it would be better to use the single official package for local testing too. I'm sure it is not required to create more branches.

**Comment by scottmarlow** [comment]
> > > @gurunrao RC3 does represent what EE 10 Platform TCK final was based on, I pushed a new tag https://github.com/eclipse-ee4j/jakartaee-tck/releases/tag/10.0.0.Final which is more clear (https://github.com/eclipse-ee4j/jakartaee-tck/tree/10.0.x is the branch for maintaining EE 10 Platform TCK).
> > 
> > 
> > post merge of PR #1112, Final TCK was built on 2022-08-16, we can refer https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee10/staged/eftl/jakarta-jakartaeetckinfo.txttck info txt for the exact timestamp. RC3 was marked on 9-Aug, which is a different date. final commits are with #1112 for Jakarta EE 10 Platform TCK and should be tagged as Final.
> 
> Good catch, agreed we should include the additional commits used in final build of Platform TCK on 2022-08-16.

@gurunrao 
https://github.com/eclipse-ee4j/jakartaee-tck/tree/10.0.x is based on the new `10.0.0.Final` tag for commit `7fa821de4abcde9e2f9a1892e47d1b686b7e94a4`

**Comment by gurunrao** [comment]
IMO we should wait for discussion thread https://www.eclipse.org/lists/jakartaee-platform-dev/msg03686.html to conclude for the PR review. We need to have different branching strategy if there is consensus on 10.1 and 11 being developed.
I would like to wait for final decision on 10.1

**Comment by scottmarlow** [comment]
> IMO we should wait for discussion thread https://www.eclipse.org/lists/jakartaee-platform-dev/msg03686.html to conclude for the PR review. We need to have different branching strategy if there is consensus on 10.1 and 11 being developed. I would like to wait for final decision on 10.1

We already have a branching strategy that works for all possible cases:

1. If we do a 10.1 release, that will be based on `10.0.x` [branch](https://github.com/eclipse-ee4j/jakartaee-tck/tree/10.0.x).  
2. If we need to do any other 10.x minor releases, they will be done via the latest 10.N.x release where `N` is the last minor done for `10`.
3. The 11 release will be based on our `master` branch.

The main advantage of not waiting for a 10.1/11 release plan is that we can complete more TCK refactoring which we are currently blocked on doing since our Jenkins CI jobs for 11 cannot run until the correct stage output folder is updated (in our git repo I believe).  We shouldn't stage any EE 11 TCKs in an EE 10 staged folder.

**Comment by gurunrao** [comment]
> > IMO we should wait for discussion thread https://www.eclipse.org/lists/jakartaee-platform-dev/msg03686.html to conclude for the PR review. We need to have different branching strategy if there is consensus on 10.1 and 11 being developed. I would like to wait for final decision on 10.1
> 
> We already have a [branching strategy](https://github.com/eclipse-ee4j/jakartaee-tck/wiki/Branch-naming) that works for all possible cases:
> 
>     1. If we do a 10.1 release, that will be based on `10.0.x` [branch](https://github.com/eclipse-ee4j/jakartaee-tck/tree/10.0.x).
> 
>     2. If we need to do any other 10.x minor releases, they will be done via the latest 10.N.x release where `N` is the last minor done for `10`.
> 
>     3. The 11 release will be based on our `master` branch.
> 
> 
> The main advantage of not waiting for a 10.1/11 release plan is that we can complete more TCK refactoring which we are currently blocked on doing since our Jenkins CI jobs for 11 cannot run until the correct stage output folder is updated (in our git repo I believe). We shouldn't stage any EE 11 TCKs in an EE 10 staged folder.

We should use git tckrefactor branch for TCK refactoring, master will be used for 10.1/11 release. Also platform TCK can be built from tckrefactor branch using CI job and can be tested, not having current PR will have no effect on tck refactoring.

**Review by gurunrao — APPROVED** [review]
LGTM

**Comment by scottmarlow** [comment]
> We should use git tckrefactor branch for TCK refactoring, master will be used for 10.1/11 release. 

Thanks @gurunrao for suggesting that, I agree with continuing the refactoring with the `tckrefactor` branch.  

Regarding `10.1` release, we could use `10.0.x` for that if we create a minor release.  Regarding specific changes for `11`, that should be done via `master` branch as you suggest.

@olamy  please confirm that continuing to refactor on the `tckrefactor` branch ^ wouldn't impact https://github.com/eclipse-ee4j/jakartaee-tck/pull/912 since you are already targeting the `tckrefactor` branch?


> Also we should build Platform TCK with JDK 17 as base as per latest platform meeting[https://docs.google.com/document/d/1DF0T2hbJqDNsY0v_lYFKCz-ZgHPbnMUIu6mhmt5LCJU/edit#]

The discussion on which JDK version to use as a base will continue for the next few weeks at least.  It seems to be a moving target.  Some want to use `JDK 11` as the target version to compile for.  Some want to use `JDK 17` as the base and others want to start with `JDK 19` and later change to `JDK 21` as the base.  

Just as an FYI, after we were about half way into the `EE 10` release, many wanted to switch to use `JDK 17` as the base.

Scott

**Comment by olamy** [comment]
@scottmarlow the branch for #912 was created on `tckrefactor` my plan actually is to rebase my work from master so to propose a PR including `tckrefactor` and my changes. something mergeable.
Because I'd like to run last servlet tck changes with the new code which is really faster to run servlet tck.
does it work for you?

**Comment by gurunrao** [comment]
> 

IMO, rebase of tckrefactor branch with master will be ideal first step, post refactor any PR on tckrefactor can deal with merge conflicts.
If we refactor local work branch, all changes which are in master and not present at tckrefactor will be part of PR(which might cause confusion for future reference).

**Comment by olamy** [comment]
> > 
> 
> IMO, rebase of tckrefactor branch with master will be ideal first step, post refactor any PR on tckrefactor can deal with merge conflicts. If we refactor local work branch(created from tckrefactor) with master, all changes which are in master and not present at tckrefactor will be part of PR(which might cause confusion for future reference).

yup makes sense as well. I can first rebase `tckrefactor` then rebase my branch on this.

@scottmarlow fine with you?

**Comment by scottmarlow** [comment]
@olamy please do rebase `tckrefactor` with latest `master` changes as @gurunrao mentioned.  I assume you will do that on a local topic branch created from `tckrefactor` (IMO, always good to do big changes like that on a throwaway branch in case you want to start over).

**Comment by olamy** [comment]
> @olamy please do rebase `tckrefactor` with latest `master` changes as @gurunrao mentioned. I assume you will do that on a local topic branch created from `tckrefactor` (IMO, always good to do big changes like that on a throwaway branch in case you want to start over).

done here https://github.com/eclipse-ee4j/jakartaee-tck/pull/1124/

would be good to merge it quickly so I can rebase the servlet branch as well.
thanks
and we need to discuss merging the servlet branch to `tckrefactor` branch as such long live branch are a nightmare to maintain :(

**Pull request merged**
