### PR TITLE
Update doc/assertions for removed rmiiiop tests

### PR DESCRIPTION
**Pull request by scottmarlow**
Signed-off-by: Scott Marlow <smarlow@redhat.com>
https://github.com/eclipse-ee4j/jakartaee-tck/issues/548

### CODE REVIEW

**Comment by alwin-joseph** [comment]
I think the right way to update JavaEESpecAssertions.xml is to generate it newly from the Jakarta-platform-spec-9.pdf document. I see several more changes required as per https://github.com/eclipse-ee4j/jakartaee-platform changes.


Step 1 : Generate JakartaEESpecAssertions.xml (rename JavaEE* to JakartaEE*) from Jakarta-platform-spec-9.pdf. The spec document can be obtained by below steps
git clone https://github.com/eclipse-ee4j/jakartaee-platform.git
cd jakartaee-platform/specification
mvn install (jdk8, mvn installation are prerequisites)
spec pdf document at target/generated-docs

Step 2 : Follow https://github.com/eclipse-ee4j/jakartaee-tck/wiki/Steps-to-generate-the-html-version-of-the-SpecAssertions.xml to generate the html version of JakartaEESpecAssertions.xml as JakartaEESpecAssertions.html

Step 3: Add both JakartaEESpecAssertions.xml and JakartaEESpecAssertions.html into the bundle

**Comment by alwin-joseph** [comment]
> I think the right way to update JavaEESpecAssertions.xml is to generate it newly from the latest Jakarta-platform-spec-9 document. I see several more changes needed for SpecAssertions.xml as per the changes in https://github.com/eclipse-ee4j/jakartaee-platform.
> 
> Step 1 : Generate JakartaEESpecAssertions.xml (rename JavaEE* to JakartaEE*) from Jakarta-platform-spec-9 doc.
> 
I do not know if there is any easy way or a tool available to generate the JakartaEESpecAssertions.xml from the Jakarta-platform-spec-9 document, Jan suggested they could be manually updated based on the spec document.  We could try the same , allow spec team to review it or get their help to generate the latest.

**Comment by scottmarlow** [comment]
> > I think the right way to update JavaEESpecAssertions.xml is to generate it newly from the latest Jakarta-platform-spec-9 document. I see several more changes needed for SpecAssertions.xml as per the changes in https://github.com/eclipse-ee4j/jakartaee-platform.
> > Step 1 : Generate JakartaEESpecAssertions.xml (rename JavaEE* to JakartaEE*) from Jakarta-platform-spec-9 doc.
> 
> I do not know if there is any easy way or a tool available to generate the JakartaEESpecAssertions.xml from the Jakarta-platform-spec-9 document, Jan suggested they could be manually updated based on the spec document. We could try the same , allow spec team to review it or get their help to generate the latest.
> cc @jeanouii

The Platform SPEC should go up for ballot by November 6th, however, we want to complete our Platform TCK changes this week (goal is to stage + promote the Platform TCK on Friday).  Then, use the promoted TCK to test a GlassFish release candidate on the weekend.  Given that we are still updating the [Platform SPEC ](https://github.com/eclipse-ee4j/jakartaee-platform/pull/255) it may not be possible to have an accurate Jakarta-platform-spec-9 document.

Having said that, I think that we should create a Jenkins job to perform these steps that you mentioned above.  I'll see if I can start that.

**Comment by alwin-joseph** [comment]
> > > I think the right way to update JavaEESpecAssertions.xml is to generate it newly from the latest Jakarta-platform-spec-9 document. I see several more changes needed for SpecAssertions.xml as per the changes in https://github.com/eclipse-ee4j/jakartaee-platform.
> > > Step 1 : Generate JakartaEESpecAssertions.xml (rename JavaEE* to JakartaEE*) from Jakarta-platform-spec-9 doc.
> > 
> > 
> > I do not know if there is any easy way or a tool available to generate the JakartaEESpecAssertions.xml from the Jakarta-platform-spec-9 document, Jan suggested they could be manually updated based on the spec document. We could try the same , allow spec team to review it or get their help to generate the latest.
> > cc @jeanouii
> 
> The Platform SPEC should go up for ballot by November 6th, however, we want to complete our Platform TCK changes this week (goal is to stage + promote the Platform TCK on Friday). Then, use the promoted TCK to test a GlassFish release candidate on the weekend. Given that we are still updating the [Platform SPEC ](https://github.com/eclipse-ee4j/jakartaee-platform/pull/255) it may not be possible to have an accurate Jakarta-platform-spec-9 document.
> 
Looks like the internal/docs will not be part of the TCK bundle and we could update the files in it (including internal/docs/jakartaee/JakartaEESpecAssertions.xml ) even after promoting the TCK bundle and platform spec is done. Is that ok? We can merge the changes in other files before that.

**Comment by scottmarlow** [comment]
> Looks like the internal/docs will not be part of the TCK bundle and we could update the files in it (including internal/docs/jakartaee/JakartaEESpecAssertions.xml ) even after promoting the TCK bundle and platform spec is done. Is that ok? We can merge the changes in other files before that.

That is an excellent point, thanks.  Yes, I agree!

**Comment by alwin-joseph** [comment]
I missed to see install/jakartaee/docs/assertions/JakartaEESpecAssertions.html which is the html version of internal/docs/jakartaee/JakartaEESpecAssertions.xml . install/jakartaee/docs/assertions/JakartaEESpecAssertions.html is part of the bundle and hence is dependent on the platform spec completion. 
Merging this PR for now , we would need to decide on whether to keep  install/jakartaee/docs/assertions/JakartaEESpecAssertions.html uptodate for promoting the TCK.

**Review by alwin-joseph — APPROVED** [review]

**Pull request merged**
