### PR TITLE
jaxrs build fix

### PR DESCRIPTION
**Pull request by RohitKumarJain**
This PR is to fix jaxrs tck build fix. Testing has been done successfully, Results can be found here: https://ci.eclipse.org/jakartaee-tck/job/jakartaee-tck-rjain/job/master/20/

Signed-off-by: RohitKumarJain <rohit.ku.jain@oracle.com>

### CODE REVIEW

**Review by scottmarlow — APPROVED** [review]
Thanks Rohit!

**Review by alwin-joseph — CHANGES_REQUESTED** [review]
Can you please check if more jars are added to the ts.harness.classpath unnecessarily. Please remove if that is not required

commons-httpclient-3.1.jar${pathsep}${ts.home}/lib/commons-logging-1.1.3.jar${pathsep}${ts.home}/lib/commons-codec-1.9.jar

**Comment by RohitKumarJain** [comment]
> Can you please check if more jars are added to the ts.harness.classpath unnecessarily. Please remove if that is not required
> 
> commons-httpclient-3.1.jar${pathsep}${ts.home}/lib/commons-logging-1.1.3.jar${pathsep}${ts.home}/lib/commons-codec-1.9.jar

thanks, @alwin-joseph  for the review. I have removed extra jar which is {ts.home}/lib/commons-codec-1.9.jar. The other two jars which is commons-httpclient-3.1.jar and commons-logging-1.1.3.jar are required.

**Comment by RohitKumarJain** [comment]
> > Can you please check if more jars are added to the ts.harness.classpath unnecessarily. Please remove if that is not required
> > commons-httpclient-3.1.jar${pathsep}${ts.home}/lib/commons-logging-1.1.3.jar${pathsep}${ts.home}/lib/commons-codec-1.9.jar
> 
> thanks, @alwin-joseph for the review. I have removed extra jar which is {ts.home}/lib/commons-codec-1.9.jar. The other two jars which is commons-httpclient-3.1.jar and commons-logging-1.1.3.jar are required.

I have removed commons-httpclient-3.1.jar and commons-logging-1.1.3.jar as well after your review. Thanks for highlighting this.

**Review by alwin-joseph — APPROVED** [review]

**Pull request merged**
