### PR TITLE
Update EFFEECTIVEVERSION=5 check in servlet tests

### PR DESCRIPTION
**Pull request by gerdogdu**
Below servlet tests are failed to check EFFECTIVEVERSION=3 but we need to check it as 5. This pull request solves this failure.

```
- com/sun/ts/tests/servlet/api/jakarta_servlet/servletcontext30/URLClient.java#getEffectiveMajorVersionTest: URLClient_getEffectiveMajorVersionTest

- com/sun/ts/tests/servlet/pluggability/api/jakarta_servlet/servletcontext30/URLClient.java#getEffectiveMajorVersionTest: URLClient_getEffectiveMajorVersionTest 
```

### CODE REVIEW

**Comment by alwin-joseph** [comment]
I was late to see this and just raised a PR to fix the EFFECTIVEVERSION at https://github.com/eclipse-ee4j/jakartaee-tck/pull/335.

**Comment by scottmarlow** [comment]
@alwin-joseph looks like a tie. Both pull requests look good, yours does also fix the REGISTRION_CLASS_NAME typo.

**Comment by gerdogdu** [comment]
@scottmarlow @alwin-joseph No problem, you can push Alwin PR.

**Comment by scottmarlow** [comment]
Thanks @gerdogdu!

**Comment by alwin-joseph** [comment]
Thanks @gerdogdu . It was coincidence I stumbled on this issue while fixing others and found your email in ml and this PR, right after raising mine.

**Pull request closed without merging**
