### PR TITLE
Test for existence of default ExceptionMapper

### PR DESCRIPTION
**Pull request by ronsigal**
Test for existence of default ExceptionMapper

### CODE REVIEW

**Comment by ronsigal** [comment]
This PR is a new test for https://github.com/eclipse-ee4j/jaxrs-api/issues/855, which requires the existence of a default ExceptionMapper.

Two questions:
1. Which branch should this change go in?
2. I don't know what the conventions are for entries in the Spec and Javadoc assertions files. Should I add something, and do new entries just go at the end?

**Comment by scottmarlow** [comment]
> Two questions:
> 
>     Which branch should this change go in?

This change should target the master branch, which is changing for EE 9, as the sources are being updated to use the EE 9 SPEC APIs.

**Comment by scottmarlow** [comment]
> I don't know what the conventions are for entries in the Spec and Javadoc assertions files. Should I add something, and do new entries just go at the end?

I'm not sure, is this for a new github.com/eclipse-ee4j/jaxrs-api specification requirement?

**Comment by ronsigal** [comment]
Hi @scottmarlow,

re: "This change should target the master branch,"

Ok, good. Thanks.

re: "is this for a new github.com/eclipse-ee4j/jaxrs-api specification requirement?"

Yes, it's a change in behavior.

-Ron

**Comment by andymc12** [comment]
HI @ronsigal - first, I think it is awesome that you are updating the TCK for this.  Since the spec/API change is going into JAX-RS 3.1 (which is post-EE9), I think that `master` is the wrong branch.  Otherwise, the TCK test will go into EE 9/JAX-RS 3.0, but implementations should not implement this new behavior until EE 10 / JAX-RS 3.1 (or higher).  

I think that this project will either need to create a post-EE9 branch for your changes or you may need to comment out (or `@Ignore`?) your tests until after EE9 is released.

HTH, Andy

**Comment by scottmarlow** [comment]
@ronsigal also, you need to sign your commits and push them again.

Regarding what to do with this pull request until we have a branch for EE 10, we could create an EE10 label and apply it to this pull request, so that is obvious that this is targeted for EE 10.

**Comment by ronsigal** [comment]
@scottmarlow, I've signed the commit. In particular, I soft reset to the previous commit, re-committed, and force pushed to my repo. It seems to have worked. 

So, there are a couple of options:

1. Change branch
2. Add a label

I'll let you guys decide. ;-)

**Comment by ronsigal** [comment]
@andymc12, re: "awesome"

Well, I don't know about that. :-D

**Comment by scottmarlow** [comment]
@ronsigal, when you do a "git log" locally, do you see the "Signed-off-by" comment for each of your commits?  They appear to be missing according to the "all checks have failed" message here.

**Comment by scottmarlow** [comment]
@ronsigal also be sure that you use "git commit -s" to sign the commit (avoid the capital S option as that is for gpg-sign).

**Comment by ronsigal** [comment]
@scottmarlow, aaaahhhh. I did -S. I'll try again.

**Comment by ronsigal** [comment]
@scottmarlow, Ok, I think it worked this time. Thanks!!

**Comment by scottmarlow** [comment]
@ronsigal or anyone else, please comment again on this pull request, when the [jaxrs-api/issues/855 ](https://github.com/eclipse-ee4j/jaxrs-api/issues/855) is planned to be in a specific Jakarta EE release.  At that time, we can determine the best branch to merge this pr to.  Thanks for your contribution!

**Comment by ronsigal** [comment]
@scottmarlow, I'll defer to "anyone else". ;-)

**Comment by andymc12** [comment]
@scottmarlow @ronsigal This will be part of JAX-RS 3.1 which is post-EE9.  It will for sure be in EE10 (though the JAX-RS version may be different for EE10 - like JAX-RS 3.2, 4.0, etc.).  Thanks!

**Comment by ronsigal** [comment]
I forgot to follow up on the question: "I don't know what the conventions are for entries in the Spec and Javadoc assertions files. Should I add something, and do new entries just go at the end?"

**Comment by bshannon** [comment]
> @scottmarlow @ronsigal This will be part of JAX-RS 3.1 which is post-EE9. It will for sure be in EE10 (though the JAX-RS version may be different for EE10 - like JAX-RS 3.2, 4.0, etc.). Thanks!

Changes for post-EE 9 work should not go into master.

I'm not sure we've defined a branching strategy for work after EE 9.  Perhaps just pick a
branch of your own (if you're allowed to create branches) and then remember to merge
it after EE 9 is done.  (I know, not perfect, but most people are too busy with EE 9 to be
thinking about EE 10.)

**Comment by jansupol** [comment]
@ronsigal This probably should go to the TCK in the Jakarta REST API repository.

**Comment by gurunrao** [comment]
@ronsigal - Please raise the same PR at https://github.com/jakartaee/rest repository, corresponding class - https://github.com/jakartaee/rest/blob/master/jaxrs-tck/src/main/java/ee/jakarta/tck/ws/rs/ee/rs/ext/providers/JAXRSProvidersClientIT.java

We are planning to close the PR at jakartaee-tck, since source for jaxrs has been removed and migrated to rest repository.

**Comment by gurunrao** [comment]
close PR based on ^ comment.

**Pull request closed without merging**
