### PR TITLE
jsf schema namespace update to jakartaee

### PR DESCRIPTION
**Pull request by alwin-joseph**

### CODE REVIEW

**Comment by alwin-joseph** [comment]
There are 8 test failures due to this change and need to be resolved.
test report : https://ci.eclipse.org/jakartaee-tck/job/jakartaee-tck-alw/job/jsfnamespace/2/

**Comment by scottmarlow** [comment]
@alwin-joseph I don't see web-facesconfig_3_0.xsd in https://github.com/eclipse-ee4j/mojarra

**Comment by scottmarlow** [comment]
@alwin-joseph did you find the first failure in the server.log file?  I looked myself but am not sure if I found the correct failure.  

I found this near the (99%) end of server.log which seems far:
```
[2020-08-24T10:16:11.296+0000] [glassfish 6.0] [WARNING] [] [jakarta.enterprise.web] [tid: _ThreadID=27 _ThreadName=http-listener-1(1)] [timeMillis: 1598264171296] [levelValue: 900] [[
  StandardWrapperValve[Faces Servlet]: Servlet.service() for servlet Faces Servlet threw exception
jakarta.faces.application.ProtectedViewException
        at com.sun.faces.lifecycle.RestoreViewPhase.maybeTakeProtectedViewAction(RestoreViewPhase.java:293)
        at com.sun.faces.lifecycle.RestoreViewPhase.execute(RestoreViewPhase.java:204)
        at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:72)
        at com.sun.faces.lifecycle.RestoreViewPhase.doPhase(RestoreViewPhase.java:102)
        at com.sun.faces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:159)
        at jakarta.faces.webapp.FacesServlet.executeLifecyle(FacesServlet.java:681)
        at jakarta.faces.webapp.FacesServlet.service(FacesServlet.java:437)
        at org.apache.catalina.core.StandardWrapper.service(StandardWrapper.java:1540)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:217)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:119)
        at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:611)
        at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:550)
        at com.sun.enterprise.web.WebPipeline.invoke(WebPipeline.java:75)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:114)
        at org.apache.catalina.connector.CoyoteAdapter.doService(CoyoteAdapter.java:332)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:199)
        at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:440)
        at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:144)
        at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:174)
        at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:153)
        at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:196)
        at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:88)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:248)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:181)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:121)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:99)
        at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:51)
        at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:510)
        at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:82)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:83)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:34)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:101)
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:535)
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:515)
        at java.lang.Thread.run(Thread.java:748)
]]
```

**Comment by alwin-joseph** [comment]
> @alwin-joseph did you find the first failure in the server.log file? I looked myself but am not sure if I found the correct failure.
> 
> I found this near the (99%) end of server.log which seems far:
> 
> ```
> [2020-08-24T10:16:11.296+0000] [glassfish 6.0] [WARNING] [] [jakarta.enterprise.web] [tid: _ThreadID=27 _ThreadName=http-listener-1(1)] [timeMillis: 1598264171296] [levelValue: 900] [[
>   StandardWrapperValve[Faces Servlet]: Servlet.service() for servlet Faces Servlet threw exception
> jakarta.faces.application.ProtectedViewException
>         at com.sun.faces.lifecycle.RestoreViewPhase.maybeTakeProtectedViewAction(RestoreViewPhase.java:293)
>         at com.sun.faces.lifecycle.RestoreViewPhase.execute(RestoreViewPhase.java:204)
>         at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:72)
>         at com.sun.faces.lifecycle.RestoreViewPhase.doPhase(RestoreViewPhase.java:102)
>         at com.sun.faces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:159)
>         at jakarta.faces.webapp.FacesServlet.executeLifecyle(FacesServlet.java:681)
>         at jakarta.faces.webapp.FacesServlet.service(FacesServlet.java:437)
>         at org.apache.catalina.core.StandardWrapper.service(StandardWrapper.java:1540)
>         at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:217)
>         at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:119)
>         at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:611)
>         at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:550)
>         at com.sun.enterprise.web.WebPipeline.invoke(WebPipeline.java:75)
>         at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:114)
>         at org.apache.catalina.connector.CoyoteAdapter.doService(CoyoteAdapter.java:332)
>         at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:199)
>         at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:440)
>         at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:144)
>         at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:174)
>         at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:153)
>         at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:196)
>         at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:88)
>         at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:248)
>         at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:181)
>         at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:121)
>         at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:99)
>         at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:51)
>         at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:510)
>         at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:82)
>         at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:83)
>         at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:34)
>         at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:101)
>         at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:535)
>         at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:515)
>         at java.lang.Thread.run(Thread.java:748)
> ]]
> ```

I see the same from a CI run not when I try in my local.

**Comment by alwin-joseph** [comment]
@arjantijms Can you please help confirm if the https://github.com/eclipse-ee4j/mojarra 3.0.0-RC3(which is integrated in glassfish) has the latest jakartaee schema updated. 
I saw both web-facesconfig_3_0.xsd and web-facesconfig_2_2.xsd references in mojarra 3.0.0-RC3 branch.
8 jsf tests are failing after updating the schema in this PR, so wanted to confirm if anything is pending in mojarra regarding the schema updates.

**Comment by gurunrao** [comment]
@scottmarlow  @alwin-joseph  - we should merge PR and create a new tracking bug at mojarra/glassfish to get  to completion(If no more changes is pending to be done at TCK for JSF schema update)

**Review by gurunrao — APPROVED** [review]
LGTM

**Comment by scottmarlow** [comment]
https://github.com/eclipse-ee4j/jakartaee-tck/pull/474 may have some similar changes but since that is blocked on connector compat 1.0 test removal, fine to merge this pr.

**Pull request merged**
