### PR TITLE
According to issue#45 making few changes

### PR DESCRIPTION
**Pull request by RohitKumarJain**

### CODE REVIEW

**Comment by markt-asf** [comment]
I see you have opted to change the context path the client expects to use for this test. That was probably the simplest approach.
I've been provided with a build of this fix and have confirmed that the tests now pass.
Finally, I do wonder if the `<context-root>` element is still required in the sun-web.xml file but it shouldn't cause any harm if it is present..

**Comment by RohitKumarJain** [comment]
It won't lead to any cause. If you feel changes are Ok, could you give sign-off for this so we can move ahead?

**Comment by RohitKumarJain** [comment]
@arjantijms , thanks.

**Comment by alwin-joseph** [comment]
@RohitKumarJain  Please use "--signoff" option from next commit.

**Comment by olamy** [comment]
this change was fine but it has been reverted here https://github.com/eclipse-ee4j/jakartaee-tck/commit/c990b0279c5f3e30699d01ef435d33835198bb3c

**Comment by olamy** [comment]
@alwin-joseph @arjantijms why this has been reverted? see https://github.com/eclipse-ee4j/jakartaee-tck/commit/c990b0279c5f3e30699d01ef435d33835198bb3c#r36410597 
cc @markt-asf

**Comment by arjantijms** [comment]
I have no idea why it was reverted, but the comment says it will be looked into “soon”.

**Comment by alwin-joseph** [comment]
> @alwin-joseph @arjantijms why this has been reverted? see [c990b02#r36410597](https://github.com/eclipse-ee4j/jakartaee-tck/commit/c990b0279c5f3e30699d01ef435d33835198bb3c#r36410597)
> cc @markt-asf

Reverting the revert in https://github.com/eclipse-ee4j/jakartaee-tck/pull/251. Sorry for the confusion.

**Pull request merged**
