### PR TITLE
Remove Authentication TCK and related contents

### PR DESCRIPTION
**Pull request by alwin-joseph**
**Related Issue(s)**
https://github.com/jakartaee/authentication/issues/166

**Describe the change**
Removes authentication tck tests (jaspic standalone TCK and related contents) as it is migrated to authentication repo via https://github.com/jakartaee/authentication/pull/167.

CC  @gurunrao @scottmarlow

### CODE REVIEW

**Comment by alwin-joseph** [comment]
This is waiting for the authentication TCK migration PR https://github.com/jakartaee/authentication/pull/167 to be merged.
 **Please do not merge this PR until that**

**Review by gurunrao — APPROVED** [review]

**Comment by gurunrao** [comment]
If no more comments, shall we merge the PR EOD?

**Comment by alwin-joseph** [comment]
> If no new comments, shall we merge the PR EOD?

The migration PR is merged and the code transfer is done. Although it would be ideal to wait till the new authentication TCK service release is complete I guess it should be ok to merge now. 

cc @scottmarlow @arjantijms

**Comment by arjantijms** [comment]
+1 to merge from me

**Review by arjantijms — APPROVED** [review]

**Pull request merged**
