### PR TITLE
Remove set.ext.dirs from GlassFish Porting kit

### PR DESCRIPTION
**Pull request by scottmarlow**
Signed-off-by: Scott Marlow <smarlow@redhat.com>

**Fixes Issue**
https://github.com/eclipse-ee4j/jakartaee-tck/issues/733

**Describe the change**
Remove set.ext.dirs for Jakarta EE 10+ / JDK 11

CC @alwin-joseph @anajosep @arjantijms @cesarhernandezgt @dblevins @m0mus @edbratt @gurunrao @jansupol @jgallimore @kazumura @kwsutter @LanceAndersen @bhatpmk @RohitKumarJain @shighbar @gthoman @brideck @scottmarlow

### CODE REVIEW

**Comment by gurunrao** [comment]
Found ext.dir references in following files:
- src/com/sun/ts/lib/util/sec/misc/Launcher.java
- src/com/sun/ts/lib/util/sec/misc/ExtensionDependency.java
- src/com/sun/ts/lib/util/sec/security/provider/PolicyParser.java
- install/websocket/bin/ts.jte
- install/connector/bin/ts.jte
- install/jakartaee/bin/ts.jte
- install/jaspic/bin/ts.jte
- install/jaxws/bin/ts.jte
- install/jacc/bin/ts.jte
- bin/xml/impl/glassfish/s1as.xml

**Comment by scottmarlow** [comment]
Do we need to remove `ext.dir` from com.sun.ts.lib.util.sec.misc.Launcher class or remove the Launcher class?

**Comment by scottmarlow** [comment]
> Do we need to remove `ext.dir` from com.sun.ts.lib.util.sec.misc.Launcher class or remove the Launcher class?

Launcher has a static instance that may be used to launch the standalone tests.  I suspect that we just need to remove the ext.dir use in various forms (extension classloader classes + support methods).

**Comment by scottmarlow** [comment]
> Found ext.dir references in following files:
> 
>     * src/com/sun/ts/lib/util/sec/misc/Launcher.java
> 
>     * src/com/sun/ts/lib/util/sec/misc/ExtensionDependency.java
> 
>     * src/com/sun/ts/lib/util/sec/security/provider/PolicyParser.java
> 
>     * install/websocket/bin/ts.jte
> 
>     * install/connector/bin/ts.jte
> 
>     * install/jakartaee/bin/ts.jte
> 
>     * install/jaspic/bin/ts.jte
> 
>     * install/jaxws/bin/ts.jte
> 
>     * install/jacc/bin/ts.jte
> 
>     * bin/xml/impl/glassfish/s1as.xml

@gurunrao  updates pushed for ^, I'll kick off a Full Platform TCK build to verify that no compilation failures are introduced.

**Review by gurunrao — APPROVED** [review]
LGTM

**Pull request merged**
