### PR TITLE
update CTS version to 8.0.2

### PR DESCRIPTION
**Pull request by scottmarlow**
Signed-off-by: Scott Marlow <smarlow@redhat.com>
For [pull/138](https://github.com/eclipse-ee4j/jakartaee-tck/pull/138)

### CODE REVIEW

**Comment by scottmarlow** [comment]
@alwin-joseph I updated [jakartaeetck-nightly-build-master](https://ci.eclipse.org/jakartaee-tck/job/jakartaeetck-nightly-build-master/configure) to use 8.0.2 and [this pull request is similar to](https://github.com/eclipse-ee4j/jakartaee-tck/commit/6efae35b6594cb570ad5b575fee07eb0c4bee00d)

**Comment by scottmarlow** [comment]
Since I already updated the jakartaeetck-nightly-build-master to use 8.0.2, this pr should get merged, @alwin-joseph could you merge it?

**Comment by scottmarlow** [comment]
@alwin-joseph I'll merge it myself. :)

**Comment by scottmarlow** [comment]
merged and started https://ci.eclipse.org/jakartaee-tck/job/jakartaeetck-nightly-build-master

**Comment by alwin-joseph** [comment]
@scottmarlow Thanks for this PR. The changes are good except you upgraded the jsonb TCK bundle version. The [commit](https://github.com/eclipse-ee4j/jakartaee-tck/commit/6efae35b6594cb570ad5b575fee07eb0c4bee00d) was to upgrade jsonb TCK along with jakartaee TCK.  If you want any other TCK version to be appended you would need to make the same change in the corresponding release/tools/*.xml file too (eg release/tools/servlet.xml). 

I presume other standalone TCK versions will also be upgraded in the near future, if so this change has taken care of jsonb TCK.

**Comment by scottmarlow** [comment]
On Tue, Dec 3, 2019, 12:47 AM Alwin Joseph <notifications@github.com> wrote:

> @scottmarlow <https://github.com/scottmarlow> Thanks for this PR. The
> changes are good except you upgraded the jsonb TCK bundle version.
>
I will fix that and run again .

**Comment by alwin-joseph** [comment]
> On Tue, Dec 3, 2019, 12:47 AM Alwin Joseph ***@***.***> wrote: @scottmarlow <https://github.com/scottmarlow> Thanks for this PR. The changes are good except you upgraded the jsonb TCK bundle version.
> I will fix that and run again .

Scott - I think it is also ok to leave this change as it is. It is possible that we require to upgrade the jsonb & other standalone TCKs for the next release.

**Comment by scottmarlow** [comment]
@alwin-joseph I think that the last jsonb change was included in the 8.0.1 TCK changes, which I assume are reflected in [jsonb-tck-1.0.1.zip](http://download.eclipse.org/ee4j/jakartaee-tck/master/nightly/jsonb-tck-1.0.1.zip), so unless more jsonb changes are expected, I would expect that updating the release/tools/jsonb.xml back to 1.0.1 would be fine.

What is the next step to release jakartaeetck-8.0.2.zip?

**Comment by alwin-joseph** [comment]
> @alwin-joseph I think that the last jsonb change was included in the 8.0.1 TCK changes, which I assume are reflected in [jsonb-tck-1.0.1.zip](http://download.eclipse.org/ee4j/jakartaee-tck/master/nightly/jsonb-tck-1.0.1.zip), so unless more jsonb changes are expected, I would expect that updating the release/tools/jsonb.xml back to 1.0.1 would be fine.
> 
Ok.
> What is the next step to release jakartaeetck-8.0.2.zip?
As of now, after the change and triggering the build job the nightly bundle jakartaeetck-8.0.2.zip is available at https://download.eclipse.org/ee4j/jakartaee-tck/master/nightly/. The job https://ci.eclipse.org/jakartaee-tck/job/jakartaeetck-nightly-run-master/ will pick this bundle and run against glassfish 5.1.0 to verify the changes. This process is for regular changes and testing and not for official release of the bundle. 
I believe to release jakartaeetck-8.0.2.zip officially it needs to undergo the same procedure as jakartaeetck-8.0.0.zip by certifying. I am not sure if there is any change on this.

**Comment by scottmarlow** [comment]
Thanks @alwin-joseph, I will make the [pull/140](https://github.com/eclipse-ee4j/jakartaee-tck/pull/140) change for reverting the jsonb tck version and look into the certification job.

**Pull request merged**
