### PR TITLE
Different results with JDK8 and JDK11 with date format in german locale

### PR DESCRIPTION
**Pull request by jbescos**
This PR is to fix this issue:
https://github.com/eclipse-ee4j/jakartaee-tck/issues/151

### CODE REVIEW

**Comment by alwin-joseph** [comment]
@jbescos  Can this change help pass the test in both JDK8 & JDK11  or is it specific to JDK11?

**Comment by jbescos** [comment]
@alwin-joseph it will pass with both.

**Comment by bshannon** [comment]
Is this fix only for Jakarta EE 9, or should it be applied to Jakarta EE 8 as well?

**Comment by jbescos** [comment]
@bshannon this fix is not related to jakarta, it is a problem with the locales in German. I think you are asking because of the other PR I have related to jakarta, but this new PR is unrelated.

Find in my example of the issue https://github.com/eclipse-ee4j/jakartaee-tck/issues/151 that the problem is reproducible using SimpleDateFormat and DateTimeFormatter.

This fix make it work from JDK8 to JDK11 (included).

**Comment by bshannon** [comment]
So to be clear, this change is applicable to the Jakarta EE 9 TCK (master branch of the TCK repo)
when using either JDK 8 or JDK 11, right?  If so, then this should be approved and merged.

What's not clear is whether this problem also occurs with the Jakarta EE 8 TCK when run with either
JDK 8 or JDK 11.  If it does apply, then someone needs to file a test challenge against Jakarta
EE 8 so that we can exclude the test from Jakarta EE 8 (we're not fixing tests in Jakarta EE 8).
Although if it does apply, I'm not sure why no one has reported it yet.  Was this a new test that
was added for Jakarta EE 9?

**Pull request merged**
