### PR TITLE
jakarta 9 pkg rename

### PR DESCRIPTION
**Pull request by frowe**

### CODE REVIEW

**Comment by scottmarlow** [comment]
Failure is due to commits not being signed:
`
Fred Rowe (frowe@****.ibm) did not include the "Signed-off-by footer" which is required for all commits made by a contributor.
` 
As per [Contributor creates a Git commit](https://wiki.eclipse.org/Development_Resources/Handling_Git_Contributions#Git)

If you did include the -s already on the git commits, perhaps you need to sign the Eclipse Agreement, as mentioned on [Contributing_via_Git](https://wiki.eclipse.org/Development_Resources/Contributing_via_Git).

**Comment by frowe** [comment]
Finally got commit signing to work properly and revalidated eca.

**Comment by frowe** [comment]
Not sure why validation check still failing, both commits are signed and I just revalidated eca.

**Comment by scottmarlow** [comment]
Is your email address associated with https://github.com/frowe, the same email address that you signed the Eclipse contributor agreement with?  

If you just resigned the Eclipse agreement, perhaps that takes some time to be accepted.

**Comment by frowe** [comment]
AFAIK, yes, same address.  I'll give the resigning some time to take affect.

**Comment by frowe** [comment]
Not sure what's causing the check fail.  When I run ECA validation, I get

> ECA validation shows “There is a valid ECA on file for frowe@*****.ibm.com”

The details link for the failed check shows 
>Fred Rowe (frowe@****.ibm) did not include the "Signed-off-by footer" which is required for all commits made by a contributor.

but I GPG signed both commits (which is in addition to regular commit signoff) as shown by the "Verified" link beside the commit hash.

**Comment by scottmarlow** [comment]
I'm not sure why but [my pr#194](https://github.com/eclipse-ee4j/jakartaee-tck/pull/194/commits) shows a green check mark by the commits but doesn't say "verified".

Your [pr commits](https://github.com/eclipse-ee4j/jakartaee-tck/pull/193/commits) shows a X in the same location and says "verified" on the right side.  

Another [pr that initially wasn't signed, but did sign as an additional step, also shows the same](https://github.com/eclipse-ee4j/jakartaee-tck/pull/191/commits).

**Comment by scottmarlow** [comment]
I pulled this pr to my local machine and do not see the git "signed off by" comment for your commits, the following is what I see:

```
git log --show-signature
commit 28fecdce7148f902fa5115797427a9988894b383 (HEAD -> frowe-tck20PkgRename)
gpg: Signature made Tue 07 Apr 2020 03:36:26 PM EDT
gpg:                using RSA key ???????????
gpg: Can't check signature: No public key
Merge: a922fa07 c51fba73
Author: Fred Rowe <frowe@us.ibm.com>
Date:   Tue Apr 7 13:36:26 2020 -0600

    Merge branch 'master' into tck20PkgRename
```

For other commits in the output, I do see the "signed off by" comment:
`
commit eaaebde4f6f1c9dd104dad7cdf7f9c25ef3bd64f
Author: Tomas Kraus <Tomas.Kraus@oracle.com>
Date:   Mon Mar 30 15:02:09 2020 +0200

    Update javax to jakarta for jakarta.xml.soap and jakarta.activation.
    
    Signed-off-by: Tomas Kraus <Tomas.Kraus@oracle.com>
`

Unrelated, for various merge commits, by me and others, I see the same, likely because the github UI doesn't use the signoff option.

**Comment by frowe** [comment]
Sorry for the churn. I was confusing signing with GPG (-S option) with signoff (-s option).  I believe the last commit fixes the problem.

**Pull request merged**
