### PR TITLE
Remove JSF/Faces TCK tests which were migrated

### PR DESCRIPTION
**Pull request by alwin-joseph**
**Fixes Issue**
https://github.com/eclipse-ee4j/jakartaee-tck/issues/908 

**Related Issue(s)**
https://github.com/jakartaee/faces/issues/1600

**Describe the change**
Removes the faces tck tests from the repository since they have been migrated to [faces](https://github.com/jakartaee/faces) via https://github.com/jakartaee/faces/pull/1649

CC @arjantijms  @gurunrao @scottmarlow

### CODE REVIEW

**Comment by gurunrao** [comment]
LGTM, will wait for PR in ready to be reviewed state.

**Review by arjantijms — APPROVED** [review]

**Comment by gurunrao** [comment]
@alwin-joseph - thanks for the PR, Please start process documented at https://github.com/eclipse-ee4j/jakartaee-platform/wiki/Guidelines_For_Standalone_TCKs

**Review by gurunrao — APPROVED** [review]
LGTM

**Comment by arjantijms** [comment]
@gurunrao can this PR be merged now?

**Comment by gurunrao** [comment]
@arjantijms  - We can merge the PR on confirmation of 5 steps listed at comment https://github.com/eclipse-ee4j/jakartaee-tck/pull/830#issuecomment-1035000513 are completed.
CC @scottmarlow

**Comment by alwin-joseph** [comment]
https://github.com/eclipse-ee4j/jakartaee-platform/wiki/Guidelines_For_Standalone_TCKs describes process around removing duplicate TCK tests from the Platform TCK.  

Below is the checklist that needs to be completed.

- [ ] Platform TCK pull request is needed to eliminate any Platform TCK tests not needed to validate Platform SPEC requirements. 
- [ ] Send email to [Platform](https://accounts.eclipse.org/mailing-list/jakartaee-platform-dev), [Platform TCK](https://accounts.eclipse.org/mailing-list/jakartaee-tck-dev), relevant SPEC API mailing lists with PR link for removing duplicate tests.
- [ ] Ensure that some validation of SPEC API is done for each tested EE container/vehicle.
- [ ] Review each test and make a determination if there is a specific Platform requirement being tested beyond just using any parts of SPEC API in specified containers.
- [ ] If the new SPEC API TCK validates the Platform requirements (with required EE container/vehicles), all of the Platform TCK tests specific to that SPEC API may be removed.

**Review by scottmarlow — APPROVED** [review]

**Comment by scottmarlow** [comment]
Thanks Alwin for your big contribution here and the new Faces TCK!

**Pull request merged**
