### PR TITLE
Convert almost all TCK User Guides to use a common template.

### PR DESCRIPTION
**Pull request by bshannon**
This is a big change to change almost all of the TCK User Guides to use a common template.
This will make it easier to update the template for all the changes related to Jakarta EE,
and then apply the updates to each TCK User Guide.

I tried to preserve the essential parts of the original TCK User Guides, mostly the compatibility
rules and the installation instructions.  Given the expected changes for Jakarta EE, exact
fidelity with all the other details didn't seem important.  Undoubtedly there is still lots of room
for further improvements.  Structural changes may be needed to the template for Jakarta EE,
which would require further customization for each TCK User Guide.

### CODE REVIEW

**Comment by bshannon** [comment]
I did not convert the javaee (platform and Web Profile) TCK UG.
It has a more complex structure that exceeded what my template
was able to handle, and it didn't seem worth the effort to update the
template to handle it.

I also haven't yet updated the JavaMail and JAF TCK UGs, which are
not in this repository.  If there are other TCK UGs not in this repository
that I should update, let me know.  BTW, where is the JAXB TCK UG?

**Comment by edbratt** [comment]
The UG is still in IP review. See CQ 19642 (I have prodded the reviewers.)

**Comment by alwin-joseph** [comment]
Hope this will be merged to EE4J_8 branch also.

**Comment by gurunrao** [comment]
@bshannon - there are 138 mention of "Java EE", shouldn't it be  "Jakarta EE"?

**Comment by bshannon** [comment]
@alwin-joseph Is the EE4J_8 branch not merged yet?  What's the holdup on that?  I thought that was supposed to be done months ago!  Let's get that done!  No, I don't plan to merge this to the EE4J_8 branch since I expect it to go away ASAP.

@gurunrao This PR isn't intended to change any of the content for Jakarta EE.  That's a huge job still to be done by someone.  This just makes it easier to make those changes.

**Pull request merged**
