### PR TITLE
Migrate JSP to XHTML in Faces TCK

### PR DESCRIPTION
**Pull request by BalusC**
**Fixes Issue**
https://github.com/jakartaee/faces/issues/1600

CC @alwin-joseph @anajosep @arjantijms @cesarhernandezgt @dblevins @m0mus @edbratt @gurunrao @jansupol @jgallimore @kazumura @kwsutter @LanceAndersen @bhatpmk @RohitKumarJain @shighbar @gthoman @brideck @scottmarlow

### CODE REVIEW

**Comment by alwin-joseph** [comment]
@BalusC Hope you can help resolve the conflicts here. These conflicting files were modified with new taglibs recently, but the changes in this PR should be accepted.

**Comment by BalusC** [comment]
Those files can just be deleted. Let me look.

**Comment by BalusC** [comment]
F5, @alwin-joseph

**Comment by alwin-joseph** [comment]
> > Technically speaking, this is not anymore the responsibility of Faces. But if you absolutely want to retain those tests
> 
> IMO, it is best to focus on finishing [Prepare new Faces TCK](https://github.com/jakartaee/faces/issues/1600#) before Faces 4.0 is final. If the new Faces 4.0 Standalone TCK is not completed in time for the `Face 4.0` release, we will then need to fix the Faces tests in the Platform TCK, which will take more time.

One of the items in https://github.com/jakartaee/faces/issues/1600 is to integrate the existing jsf TCK tests from this repo to the new TCK and disabling whatever doesn't work https://github.com/jakartaee/faces/issues/1600#issue-1113088190 . 
Agree the priority should be to complete the tests in new TCK.

**Review by scottmarlow — APPROVED** [review]

**Pull request merged**
