### PR TITLE
#937 Remove use of Applet API

### PR DESCRIPTION
**Pull request by scottmarlow**
Signed-off-by: Scott Marlow <smarlow@redhat.com>

**Fixes Issue**
https://github.com/eclipse-ee4j/jakartaee-tck/issues/937 in support of https://github.com/eclipse-ee4j/jakartaee-platform/issues/298

**Describe the change**
Applet is deprecated as of Java SE 17 and was removed from the EE 10 Platform SPEC.  This change is removing the tests that use the Applet APIs.

CC @markt-asf  @alwin-joseph @anajosep @arjantijms @cesarhernandezgt @dblevins @m0mus @edbratt @gurunrao @jansupol @jgallimore @kazumura @kwsutter @LanceAndersen @bhatpmk @RohitKumarJain @shighbar @gthoman @brideck @scottmarlow

### CODE REVIEW

**Comment by markt-asf** [comment]
Given the removal of support for NPAPI by browsers, we probably need to look at deprecating and removing `<jsp:plugin>` and associated structures. I could get the work done for that fairly quickly (in the next 24-28 hours) but is it practical to get that done for Jakarta EE 10?

Given the specs will still support `<jsp:plugin>` where use of applet is valid, this change seems like the simplest way forward for the TCK.

**Comment by starksm64** [comment]
I would say that is the correct thing to do. Remove it from the spec and update the spec documents in the PR.
https://github.com/jakartaee/specifications/pull/435

**Comment by markt-asf** [comment]
Removal without prior deprecation would be unusual. I'd want to ensure there was wide support for that. It would also require moving to 4.0.0 which triggers a bunch of other processes. I'm not sure there is time to do this at this point.

Deprecation and a change to make the `<jsp:plugin>` a NO-OP could be done in the next 24 hours or so - including updating the TCK tests to ensure that they were NO-OPs (rather than removing the tests).

**Comment by scottmarlow** [comment]
> Deprecation and a change to make the `<jsp:plugin>` a NO-OP could be done in the next 24 hours or so - including updating the TCK tests to ensure that they were NO-OPs (rather than removing the tests).

So the TCK tests would be updated to fail if the jsp:plugin is not ignored, that sounds good.

**Comment by markt-asf** [comment]
PR for changes to Jakarta Pages: https://github.com/eclipse-ee4j/jsp-api/pull/228
Feedback welcome (on that PR please).

**Pull request closed without merging**
