### PR TITLE
javax_faces folder name and references changed to jakarta_faces

### PR DESCRIPTION
**Pull request by alwin-joseph**
Signed-off-by: alwin-joseph <alwin.joseph@oracle.com>

### CODE REVIEW

**Comment by alwin-joseph** [comment]
Github is picking the folder name change correctly as "File renamed without changes. "
But for [folder name change + file content] change is viewed as a new file for the review. 

The only changes in this PR are as below:
-rename src/com/sun/ts/tests/jsf/api/javax_faces to src/com/sun/ts/tests/jsf/api/jakarta_faces
-replace javax_faces with jakarta_faces in files including the files under src/com/sun/ts/tests/jsf/api/jakarta_faces.
-correct copyright year in modified files.

**Comment by alwin-joseph** [comment]
This is to resolve https://github.com/eclipse-ee4j/jakartaee-tck/issues/240

**Comment by scottmarlow** [comment]
> Github is picking the folder name change correctly as "File renamed without changes. "
> But for [folder name change + file content] change is viewed as a new file for the review.
> 

Thanks for the note, I will review on my local machine with a higher diff.renameLimit set in .git/config.

**Comment by scottmarlow** [comment]
diff.renameLimit didn't help as much as expected, switched to use gitg instead, that is looking better.

**Comment by scottmarlow** [comment]
For renaming files, did you script the git mv or use an ide?  Just curious as we will need to do more of that.

**Comment by alwin-joseph** [comment]
> For renaming files, did you script the git mv or use an ide? Just curious as we will need to do more of that.

I used git mv

**Comment by scottmarlow** [comment]
thanks @alwin-joseph!

**Pull request merged**
