### PR TITLE
update JNLP memory to 3gb (a little higher than 2176Mi) as 6GB may be too big (Jenkins ran for about an hour and was still looking for a large enough node to use)

### PR DESCRIPTION
**Pull request by scottmarlow**
Signed-off-by: Scott Marlow <smarlow@redhat.com>

### CODE REVIEW

**Comment by alwin-joseph** [comment]
The max(limit) memory & cpu for each agent will be fixed.
means the ( max memory for jakartaeetck-ci container+ max memory for james-mail container  + max memory for jnlp container) will be fixed . Similarly for the cpu too. So I think increasing anyone can affect the utilization on other containers too.

I dont remember the correct maximum number currently applied to the agents in CI.

If this change does not solve we can request the eclipse infra guys(mikael/Fred) to provide the maximum available memory & CPU for each agents in the CI now and review our configuration.

**Comment by scottmarlow** [comment]
with 3gb, the Jenkins test jobs are running again.  If we see any overall improvement in stability, that will be a hint that we need to better configure memory use.  We could also break up the current TCK tests into small groups.

Currently, I see 24 nodes running TCK tests via https://ci.eclipse.org/jakartaee-tck/computer (with jobs still pending for an available node to run on).  I'm not sure of how many nodes were running when we had the TCK Jenkins JNLP memory size at 2176MB, however, I think we need to get stability in our jobs.

I agree it would be helpful to understand total available memory + CPU.  

For general knowledge, the [configure-pod-container/assign-memory-resource](https://kubernetes.io/docs/tasks/configure-pod-container/assign-memory-resource) describes setting a memory request (initial memory size that it at least needs) and limit (max memory size that we can grow to).  We are only setting a memory limit currently.  

If we find that some tests require less memory, we should determine the minimum memory size and set limit to that.

**Comment by scottmarlow** [comment]
https://ci.eclipse.org/jakartaee-tck/job/jakartaee-tck/job/master/735/console is still running, when it is done we should have our answer if using 3gb helps.

**Comment by scottmarlow** [comment]
@alwin-joseph it looks like the increase to 3gb helped, as in the end of the consoleText output (which I downloaded), I see the following unexpected output (at the end of appmanagedNoTx test run):

```
   [runcts] OUT => [javatest.batch] ********************************************************************************
   [runcts] OUT => [javatest.batch] Finished Test:  PASSED........com/sun/ts/tests/jpa/jpa22/repeatable/namedstoredprocedurequery/Client.java#createStoredProcedureQueryStringTest_from_appmanagedNoTx
   [runcts] OUT => [javatest.batch] ********************************************************************************
   [runcts] OUT => [javatest.batch] Number of tests completed:  1873 (1873 passed, 0 failed, 0 with errors)
   [runcts] OUT => [javatest.batch] Number of tests remaining:  9170
   [runcts] OUT => [javatest.batch] 06-30-2020 05:57:06:  Harness - Undeploying apps...
   [runcts] OUT => [javatest.batch] 06-30-2020 05:57:06:  Harness - AutoDeployment.isDeployed()
   [runcts] OUT => [javatest.batch] 06-30-2020 05:57:06:  Harness - AutoDeployment.undeploy()
   [runcts] OUT => [javatest.batch]
   [runcts] OUT => [javatest.batch] -undeploy:
   [runcts] OUT => [javatest.batch]   [gf.echo] Undeploying:  /root/jakartaeetck/bin/xml/../../dist/com/sun/ts/tests/jpa/jpa22/repeatable/namedstoredprocedurequery/jpa_jpa22_repeatable_namedstoredprocedure_vehicles.ear
   [runcts] OUT => [javatest.batch]   [gf.echo] 1 archive(s) to undeploy
   [runcts] OUT => [javatest.batch]   [gf.echo] Undeploying archive:  jpa_jpa22_repeatable_namedstoredprocedure_vehicles.ear
   [runcts] OUT => [javatest.batch]   [gf.echo] Undeployment Succeeded:  jpa_jpa22_repeatable_namedstoredprocedure_vehicles.ear
   [runcts] OUT => [javatest.batch] Successfully undeployed app:  /root/jakartaeetck/bin/xml/../../dist/com/sun/ts/tests/jpa/jpa22/repeatable/namedstoredprocedurequery/jpa_jpa22_repeatable_namedstoredprocedure_vehicles.ear
   [runcts] OUT => [javatest.batch] Undeployed apps from - /root/jakartaeetck/bin/xml/../../dist/com/sun/ts/tests/jpa/jpa22/repeatable/namedstoredprocedurequery
   [runcts] OUT => [javatest.batch] Successfully removed JMS connection factories from server 1.
   [runcts] OUT => [javatest.batch] Successfully removed JMS connection factories from server 2.
   [runcts] OUT => [javatest.batch] ********************************************************************************
   [runcts] OUT => [javatest.batch] Completed running 1873 tests.
   [runcts] OUT => [javatest.batch] Number of Tests Passed      = 1873
   [runcts] OUT => [javatest.batch] Number of Tests Failed      = 0
   [runcts] OUT => [javatest.batch] Number of Tests with Errors = 0
```

Do you know why we see ```Number of tests remaining:  9170``` when we have completed running the appmanagedNoTx vehicle tests?  Is that a side effect of using the ```_VehicleName``` support?

**Comment by alwin-joseph** [comment]
> @alwin-joseph it looks like the increase to 3gb helped, as in the end of the consoleText output (which I downloaded), I see the following unexpected output (at the end of appmanagedNoTx test run):
> 
> ```
>    [runcts] OUT => [javatest.batch] ********************************************************************************
>    [runcts] OUT => [javatest.batch] Finished Test:  PASSED........com/sun/ts/tests/jpa/jpa22/repeatable/namedstoredprocedurequery/Client.java#createStoredProcedureQueryStringTest_from_appmanagedNoTx
>    [runcts] OUT => [javatest.batch] ********************************************************************************
>    [runcts] OUT => [javatest.batch] Number of tests completed:  1873 (1873 passed, 0 failed, 0 with errors)
>    [runcts] OUT => [javatest.batch] Number of tests remaining:  9170
>    [runcts] OUT => [javatest.batch] 06-30-2020 05:57:06:  Harness - Undeploying apps...
>    [runcts] OUT => [javatest.batch] 06-30-2020 05:57:06:  Harness - AutoDeployment.isDeployed()
>    [runcts] OUT => [javatest.batch] 06-30-2020 05:57:06:  Harness - AutoDeployment.undeploy()
>    [runcts] OUT => [javatest.batch]
>    [runcts] OUT => [javatest.batch] -undeploy:
>    [runcts] OUT => [javatest.batch]   [gf.echo] Undeploying:  /root/jakartaeetck/bin/xml/../../dist/com/sun/ts/tests/jpa/jpa22/repeatable/namedstoredprocedurequery/jpa_jpa22_repeatable_namedstoredprocedure_vehicles.ear
>    [runcts] OUT => [javatest.batch]   [gf.echo] 1 archive(s) to undeploy
>    [runcts] OUT => [javatest.batch]   [gf.echo] Undeploying archive:  jpa_jpa22_repeatable_namedstoredprocedure_vehicles.ear
>    [runcts] OUT => [javatest.batch]   [gf.echo] Undeployment Succeeded:  jpa_jpa22_repeatable_namedstoredprocedure_vehicles.ear
>    [runcts] OUT => [javatest.batch] Successfully undeployed app:  /root/jakartaeetck/bin/xml/../../dist/com/sun/ts/tests/jpa/jpa22/repeatable/namedstoredprocedurequery/jpa_jpa22_repeatable_namedstoredprocedure_vehicles.ear
>    [runcts] OUT => [javatest.batch] Undeployed apps from - /root/jakartaeetck/bin/xml/../../dist/com/sun/ts/tests/jpa/jpa22/repeatable/namedstoredprocedurequery
>    [runcts] OUT => [javatest.batch] Successfully removed JMS connection factories from server 1.
>    [runcts] OUT => [javatest.batch] Successfully removed JMS connection factories from server 2.
>    [runcts] OUT => [javatest.batch] ********************************************************************************
>    [runcts] OUT => [javatest.batch] Completed running 1873 tests.
>    [runcts] OUT => [javatest.batch] Number of Tests Passed      = 1873
>    [runcts] OUT => [javatest.batch] Number of Tests Failed      = 0
>    [runcts] OUT => [javatest.batch] Number of Tests with Errors = 0
> ```
> 
> Do you know why we see `Number of tests remaining: 9170` when we have completed running the appmanagedNoTx vehicle tests? Is that a side effect of using the `_VehicleName` support?

I think so too. I have noticed that long time back, but did not try to check further. But we did verify the total count of tests in all the vehicles to match that with javaee8 resutls.

**Comment by alwin-joseph** [comment]
> @alwin-joseph it looks like the increase to 3gb helped, 

Great, thanks!

**Pull request merged**
