### PR TITLE
rebase tckrefactor branch from master branch

### PR DESCRIPTION
**Pull request by olamy**

### CODE REVIEW

**Comment by scottmarlow** [comment]
Thanks @olamy for creating the pull request!

Did you simply `git rebase master`?

**Comment by olamy** [comment]
@scottmarlow I actually did `git merge master`
would you prefer `rebase`?

**Comment by scottmarlow** [comment]
> @scottmarlow I actually did `git merge master` would you prefer `rebase`?

`git merge master` sounds better than `rebase`.  

After you did the `git merge master`, did you need to resolve a lot of conflicts?

**Comment by scottmarlow** [comment]
The `jaspic` tests should be removed as they are no longer part of the [Platform TCK](https://github.com/eclipse-ee4j/jakartaee-tck/tree/master/src/com/sun/ts/tests).

**Comment by scottmarlow** [comment]
@olamy regarding the (`The author(s) of the pull request is not covered by necessary legal agreements`) check failure that sounds like you might of used an email address that isn't associated with your Eclipse account that you signed the ECA with.

**Comment by olamy** [comment]
@scottmarlow my commits are fine and pass ECA validation. But some others from `master` branch doesn't ;) see details here https://accounts.eclipse.org/legal/eca/validation/123566

**Comment by olamy** [comment]
> > @scottmarlow I actually did `git merge master` would you prefer `rebase`?
> 
> `git merge master` sounds better than `rebase`.
> 
> After you did the `git merge master`, did you need to resolve a lot of conflicts?

some for sure. especially some xml files.

**Comment by olamy** [comment]
> The `jaspic` tests should be removed as they are no longer part of the [Platform TCK](https://github.com/eclipse-ee4j/jakartaee-tck/tree/master/src/com/sun/ts/tests).

jaspic removed

**Review by scottmarlow — APPROVED** [review]

**Comment by alwin-joseph** [comment]
@olamy 

I suspect this PR added back some contents which were deleted in master.

Below folders have different subfolders: 
- https://github.com/jakartaee/platform-tck/tree/master/src/com/sun/ts/tests/jaxrs
- https://github.com/jakartaee/platform-tck/tree/tckrefactor/jaxrs/src/test/java/com/sun/ts/tests/jaxrs

Also the below files are different (even though jaxrs/api folder is to be removed):
- [https://github.com/jakartaee/platform-tck/blob/585a6fd07bba6850ffecf4200f8719f411c[…]rc/com/sun/ts/tests/jaxrs/api/client/entity/AnnotatedClass.java](https://github.com/jakartaee/platform-tck/blob/585a6fd07bba6850ffecf4200f8719f411c76d47/src/com/sun/ts/tests/jaxrs/api/client/entity/AnnotatedClass.java)
- https://github.com/jakartaee/platform-tck/blob/tckrefactor/jaxrs/src/test/java/com/sun/ts/tests/jaxrs/api/client/entity/AnnotatedClass.java
The new contents in came from [https://github.com/jakartaee/platform-tck/blob/master/glassfish-runner/cdi-model-t[…]c/test/java/org/jboss/weld/lang/model/tck/CleanupExtension.java](https://github.com/jakartaee/platform-tck/blob/master/glassfish-runner/cdi-model-tck/src/test/java/org/jboss/weld/lang/model/tck/CleanupExtension.java)
Must have been copied wrongly ? 

If this is the only such case I guess we can correct this and move on.
Agree that it is difficult to review this PR. Maybe we should compare each module once before we start refactoring them.

cc @scottmarlow @gurunrao

**Comment by scottmarlow** [comment]
@alwin-joseph https://github.com/jakartaee/platform-tck/pull/1131 is for removing test buckets that were deleted in master.  I don't think pr 1131 addresses the problems you found though so those should be fixed also.

**Comment by olamy** [comment]
good catch. this should be fixed by this PR https://github.com/jakartaee/platform-tck/pull/1149

**Pull request merged**
