### PR TITLE
userguide & doc updates for EL

### PR DESCRIPTION
**Pull request by alwin-joseph**
Signed-off-by: alwin-joseph <alwin.joseph@oracle.com>

### CODE REVIEW

**Comment by arjantijms** [comment]
@edbratt 

>  Jenkins tests on CentOS 7.

Do you mean http://ci.eclipse.org? At least for the standalone TCKs for the individual projects, e.g. https://ci.eclipse.org/servlet I get the following:

```
OS4=3.12.0 NAME="Alpine Linux" ID=alpine VERSION_ID=3.12.0 PRETTY_NAME="Alpine Linux v3.12" HOME_URL="https://alpinelinux.org/" BUG_REPORT_URL="https://bugs.alpinelinux.org/"

JDK_VERSION=Picked up JAVA_TOOL_OPTIONS: -XX:+IgnoreUnrecognizedVMOptions -XX:+UnlockExperimentalVMOptions java version "1.8.0_202" Java(TM) SE Runtime Environment (build 1.8.0_202-b08) Java HotSpot(TM) 64-Bit Server VM (build 25.202-b08, mixed mode)
```

**Comment by scottmarlow** [comment]
https://github.com/eclipse-ee4j/jakartaee-tck/pull/398 is for showing contents of cat /etc/os-release in run_jakartaeetck.sh which should give us confirmation of which OS is used for running the Platform TCK.

I looked in https://github.com/eclipse-cbi/jiro/blob/master/instances/ee4j.jakartaee-tck/target/jenkins/configuration.yml and see references to CentOS 7 + CentOS 8.

**Comment by alwin-joseph** [comment]
> This looks good to me now. Please decide what you want to use for the OS Platform in intro.adoc, but for my purposes, this is approved.

Yes the current Eclipse CI for jakartaee-tck uses CentOS:7 for all TCK runs.

**Comment by alwin-joseph** [comment]
> @edbratt
> 
> > Jenkins tests on CentOS 7.
> 
> Do you mean http://ci.eclipse.org? At least for the standalone TCKs for the individual projects, e.g. https://ci.eclipse.org/servlet I get the following:
> 
> ```
> OS4=3.12.0 NAME="Alpine Linux" ID=alpine VERSION_ID=3.12.0 PRETTY_NAME="Alpine Linux v3.12" HOME_URL="https://alpinelinux.org/" BUG_REPORT_URL="https://bugs.alpinelinux.org/"
> 
> JDK_VERSION=Picked up JAVA_TOOL_OPTIONS: -XX:+IgnoreUnrecognizedVMOptions -XX:+UnlockExperimentalVMOptions java version "1.8.0_202" Java(TM) SE Runtime Environment (build 1.8.0_202-b08) Java HotSpot(TM) 64-Bit Server VM (build 25.202-b08, mixed mode)
> ```

The TCK runs from https://ci.eclipse.org/jakartaee-tck/ uses docker container (https://github.com/eclipse-ee4j/jakartaee-tck/blob/master/docker-images/cts-base/Dockerfile2) . Other CI instances and tck runs might be using different platforms. It would be good to append to the list if more such are available like for servlet tck can have centos:7 & Alpine Linux v3.12.

**Comment by edbratt** [comment]
This is being discussed in multiple places. Please send a clear note to the group what the base list of OS and OS versions we want to list for TCKs run in Jakarta EE TCK CI.  If a committer group wants to extend for their component (i.e. Mac OS, Maybe Windows, whatever) they can extend the list. My opinion is, we should list what we test and what we're willing to take issues/questions on.

**Pull request merged**
