### PR TITLE
find -name "*.java" -type f| xargs sed -i 's/javax\.ejb\./jakarta\.ejb\./g'

### PR DESCRIPTION
**Pull request by scottmarlow**
Signed-off-by: Scott Marlow <smarlow@redhat.com>

### CODE REVIEW

**Comment by scottmarlow** [comment]
This is too big to review and we only changed the *.java files, still need to also change *.xml + other extensions (just cannot do a "*" or "*.*" to match all files, as that would destroy any .git files that have javax in it, I already did that once, won't repeat it).

**Comment by scottmarlow** [comment]
Switching over to ag tool, thanks for the tip Jesper!

So, with ag tool, its easier to update all files that contain javax.ejb, to instead use jakarta.ejb.
`ag --ignore .git  -l javax.ejb | xargs sed -i 's/javax\.ejb\./jakarta\.ejb\./g'`

I'll push the changes from that as a separate commit.

**Comment by alwin-joseph** [comment]
@scottmarlow Thanks for taking this up. I am currently working on fixing  the signature files and related files in PR https://github.com/eclipse-ee4j/jakartaee-tck/pull/169 .
There is a chance that the changes in this PR overlap. Is it possible to exclude the changes to the files in that PR. 

The files are 
-all files under src/com/sun/ts/tests/signaturetest/signature-repository/
- *.map, *.txt
-*.xml under install/ directory

**Comment by scottmarlow** [comment]
thanks @alwin-joseph , I'll exclude src/com/sun/ts/tests/signaturetest/signature-repository/ changes from this pr.

**Comment by scottmarlow** [comment]
@alwin-joseph should be all set now, probably best for your changes to get merged first.

**Comment by scottmarlow** [comment]
@alwin-joseph I'm thinking of modifying the commits on this PR, to also update the copyright date to include 2020, sound okay?  

Does anyone know a reasonable way to review 5000 line+ pull requests?  Rely on the compiler?  Split it into reviewable pieces?  Hope for the best? :)

**Comment by scottmarlow** [comment]
I added year 2020 to the copyright notices in sources via https://github.com/fwolf/copyright-year-updater.sh, seemed to work well enough.

**Comment by scottmarlow** [comment]
I'll work out the conflicts next.

**Comment by scottmarlow** [comment]
@alwin-joseph @jansupol fyi, I just merged this, any concerns?  I should of asked for someone to approve in advance, for a big change like this.

**Pull request merged**
